"""empty message

Revision ID: 5db65791fc80
Revises: 
Create Date: 2022-04-16 17:44:39.130625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db65791fc80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wf_run',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('launch_time', sa.DateTime(), nullable=True),
    sa.Column('wf_spec_id', sa.String(), nullable=False),
    sa.Column('wf_run_id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('LAUNCHING', 'LAUNCHED', 'FAILED_LAUNCH', 'SUCCEEDED', 'FALIED_ACCEPTABLE', 'FAILED_UNACCEPTABLE', name='teststatus'), nullable=False),
    sa.Column('harness_worker_partition', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('wf_run_id')
    )
    op.create_table('task_run',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('execution_time', sa.DateTime(), nullable=True),
    sa.Column('wf_spec_id', sa.String(), nullable=False),
    sa.Column('wf_run_id', sa.String(), nullable=False),
    sa.Column('thread_run_id', sa.Integer(), nullable=False),
    sa.Column('task_run_number', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.String(), nullable=True),
    sa.Column('stderr', sa.String(), nullable=True),
    sa.Column('task_def', sa.String(), nullable=True),
    sa.Column('harness_worker_partition', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wf_run_id'], ['wf_run.wf_run_id'], ),
    sa.PrimaryKeyConstraint('wf_run_id', 'thread_run_id', 'task_run_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_run')
    op.drop_table('wf_run')
    # ### end Alembic commands ###
