"""This module defines configuration used by the python task worker.
"""
import os

KAFKA_BOOTSTRAP_SERVERS_KEY = "LHORSE_KAFKA_BOOTSTRAP_SERVERS"
KAFKA_BOOTSTRAP_SERVERS = os.getenv(
    KAFKA_BOOTSTRAP_SERVERS_KEY,
    "localhost:9092",
)

KAFKA_APPLICATION_ID_KEY = "LHORSE_KAFKA_APPLICATION_ID"
KAFKA_APPLICATION_ID = os.getenv(
    KAFKA_APPLICATION_ID_KEY,
    "unset-app-id-bad-bad-bad",
)

KAFKA_APPLICATION_IID_KEY = "LHORSE_KAFKA_APPLICATION_IID"
KAFKA_APPLICATION_IID = os.getenv(
    KAFKA_APPLICATION_IID_KEY,
    "unset-app-iid-bad-bad-bad",
)

TASKDEF_ID_KEY = "LHORSE_TASKDEF_ID"

KAFKA_POLL_PERIOD_KEY = "LHORSE_KAFKA_POLL_PERIOD"
KAFKA_POLL_PERIOD = float(os.getenv(
    KAFKA_POLL_PERIOD_KEY, "0.1"
))

EXECUTOR_NUM_THREADS_KEY = "LHORSE_EXECUTOR_NUM_THREADS"
EXECUTOR_NUM_THREADS = int(os.getenv(
    EXECUTOR_NUM_THREADS_KEY, "32"
))

TASK_MODULE_NAME_KEY = "LHORSE_TASK_MODULE_NAME"
TASK_FUNC_NAME_KEY = "LHORSE_TASK_FUNC_NAME"