---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    network_mode: "host"
  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    network_mode: "host"

  little-horse-api:
    build: .
    # image: little-horse-api:latest
    container_name: little-horse-api
    depends_on:
      - broker
    environment:
      LHORSE_KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
      LHORSE_API_URL: "http://localhost:5000"
      LHORSE_ADVERTISED_PORT: "5000"
      LHORSE_ADVERTISED_HOST: "localhost"
      LHORSE_ADVERTISED_PROTO: "http"
      LHORSE_DEFAULT_PARTITIONS: "1"
      LHORSE_DEFAULT_REPLICAS: "1"
    network_mode: "host"
    entrypoint:
      - 'java'
      - '-jar'
      - '/littleHorse.jar'
    command:
      - "api"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
