/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.littlehorse;

import java.util.Map;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.littlehorse.common.LHConfig;
import io.littlehorse.common.model.wfrun.WFRunEvent;
import io.littlehorse.scheduler.Scheduler;

class Foo {
    public int bar;
}

public class App {

    public static void experiment() throws Exception {
        String data = "{\"wfRunId\":\"asdfasdf\",\"runRequest\":{\"wfSpecId\":\"profile_workflow\",\"wfRunId\":\"21489hgasdfldj2th4poajfdslkfj\",\"variableValues\":{}}}";

        ObjectMapper mapper = new ObjectMapper();
        WFRunEvent value = mapper.readValue(data, WFRunEvent.class);
        System.out.println(value.getWfRunId());

        for (int i = 0; i < 100; i++) {
            mapper.readValue(data, Map.class);
        }

        long start = System.nanoTime();
        mapper.readValue(data, Map.class);
        System.out.println(System.nanoTime() - start);
    }

    public static void doMain(String[] args) throws Exception {
        LHConfig conf = new LHConfig();
        Scheduler.run(conf);
    }

    public static void main(String[] args) throws Exception {
        // experiment();
        doMain(args);
    }
}
