/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.littlehorse;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("TODO: run some experiment for funsies.");
        System.out.println("This class does nothing, all the logic is elsewhere.");
    }
}
