/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package little.horse;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void taskGetsScheduled() {
        System.out.println("TODO: Write unit tests");
    }
}
