/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package little.horse;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        // App classUnderTest = new App();
        assertNotNull(1234, "TODO: Test something useful");
    }
}
