---
version: '3'
services:
  zookeeper:
    labels:
      - io.littlehorse/active=true
    image: confluentinc/cp-zookeeper:6.2.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    network_mode: "host"
  broker:
    image: confluentinc/cp-kafka:6.2.4
    container_name: broker
    labels:
      - io.littlehorse/active=true
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: '127.0.0.1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092,PLAINTEXT_HOST://127.0.0.1:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    network_mode: "host"

  db:
    image: postgres
    container_name: postgres
    restart: always
    network_mode: "host"
    labels:
      - io.littlehorse/active=true
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
