# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: little-horse-test-db
    restart: always
    network_mode: "host"
    labels:
      - io.littlehorse/active=true
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
