/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url = uri("https://packages.confluent.io/maven/")
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Stuff for Javalin
    implementation("io.javalin:javalin:4.1.1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.4")
    implementation("org.slf4j:slf4j-simple:1.7.31")

    // Stuff for Kafka
    implementation("org.apache.kafka:kafka-clients:3.0.0")
    implementation("org.apache.kafka:kafka-streams:3.0.0")

    // Kubernetes cient
    implementation("io.kubernetes:client-java:10.0.0")
}

application {
    // Define the main class for the application.
    mainClass.set("little.horse.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
