// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

public final class LhProto {
  private LhProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_VariableValuePb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_VariableValuePb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_TaskRunPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_TaskRunPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_ThreadRunPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_ThreadRunPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_ThreadRunPb_VariablesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_ThreadRunPb_VariablesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_WFRunPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_WFRunPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_WFRunRequestPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_WFRunRequestPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_WFRunRequestPb_VariableValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_WFRunRequestPb_VariableValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_TaskScheduleRequestPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_TaskScheduleRequestPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_TaskScheduleRequestPb_VariableValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_TaskScheduleRequestPb_VariableValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_TaskStartedEventPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_TaskStartedEventPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_TaskCompletedEventPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_TaskCompletedEventPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_WFRunEventPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_WFRunEventPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_VariableDefPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_VariableDefPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_EdgePb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_EdgePb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_NodePb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_NodePb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_ThreadSpecPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_ThreadSpecPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lh_proto_WFSpecPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lh_proto_WFSpecPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016lh_proto.proto\022\010lh_proto\032\037google/proto" +
      "buf/timestamp.proto\"S\n\017VariableValuePb\022&" +
      "\n\004type\030\001 \001(\0162\030.lh_proto.VariableTypePb\022\030" +
      "\n\020serialized_value\030\002 \001(\014\"\376\003\n\tTaskRunPb\022\021" +
      "\n\twf_run_id\030\001 \001(\t\022\031\n\021thread_run_number\030\002" +
      " \001(\005\022\026\n\016order_position\030\003 \001(\005\022\016\n\006number\030\004" +
      " \001(\005\022\021\n\tnode_name\030\005 \001(\t\022\017\n\007node_id\030\006 \001(\t" +
      "\022\023\n\013task_def_id\030\007 \001(\t\022\026\n\tworker_id\030\010 \001(\t" +
      "H\000\210\001\001\022\026\n\016attempt_number\030\t \001(\005\022$\n\006status\030" +
      "\n \001(\0162\024.lh_proto.LHStatusPb\022\023\n\006stdout\030\013 " +
      "\001(\014H\001\210\001\001\022\023\n\006stderr\030\014 \001(\014H\002\210\001\001\022\030\n\013return_" +
      "code\030\r \001(\005H\003\210\001\001\0222\n\016scheduled_time\030\016 \001(\0132" +
      "\032.google.protobuf.Timestamp\0220\n\014started_t" +
      "ime\030\017 \001(\0132\032.google.protobuf.Timestamp\022.\n" +
      "\nended_time\030\020 \001(\0132\032.google.protobuf.Time" +
      "stampB\014\n\n_worker_idB\t\n\007_stdoutB\t\n\007_stder" +
      "rB\016\n\014_return_code\"\256\002\n\013ThreadRunPb\0227\n\tvar" +
      "iables\030\001 \003(\0132$.lh_proto.ThreadRunPb.Vari" +
      "ablesEntry\022-\n\020active_task_runs\030\002 \003(\0132\023.l" +
      "h_proto.TaskRunPb\022$\n\006status\030\003 \001(\0162\024.lh_p" +
      "roto.LHStatusPb\022\031\n\014current_node\030\004 \001(\tH\000\210" +
      "\001\001\022\030\n\020thread_spec_name\030\005 \001(\t\032K\n\016Variable" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022(\n\005value\030\002 \001(\0132\031.lh_" +
      "proto.VariableValuePb:\0028\001B\017\n\r_current_no" +
      "de\"\201\002\n\007WFRunPb\022\n\n\002id\030\001 \001(\t\022\022\n\nwf_spec_id" +
      "\030\002 \001(\t\022\024\n\014wf_spec_name\030\003 \001(\t\022.\n\nstart_ti" +
      "me\030\004 \001(\0132\032.google.protobuf.Timestamp\0221\n\010" +
      "end_time\030\005 \001(\0132\032.google.protobuf.Timesta" +
      "mpH\000\210\001\001\022$\n\006status\030\006 \001(\0162\024.lh_proto.LHSta" +
      "tusPb\022*\n\013thread_runs\030\007 \003(\0132\025.lh_proto.Th" +
      "readRunPbB\013\n\t_end_time\"\320\001\n\016WFRunRequestP" +
      "b\022\021\n\twf_run_id\030\001 \001(\t\022\022\n\nwf_spec_id\030\002 \001(\t" +
      "\022E\n\017variable_values\030\003 \003(\0132,.lh_proto.WFR" +
      "unRequestPb.VariableValuesEntry\032P\n\023Varia" +
      "bleValuesEntry\022\013\n\003key\030\001 \001(\t\022(\n\005value\030\002 \001" +
      "(\0132\031.lh_proto.VariableValuePb:\0028\001\"\262\002\n\025Ta" +
      "skScheduleRequestPb\022\023\n\013task_def_id\030\001 \001(\t" +
      "\022\025\n\rtask_def_name\030\002 \001(\t\022\031\n\021thread_run_nu" +
      "mber\030\004 \001(\t\022\027\n\017task_run_number\030\005 \001(\t\022\031\n\021t" +
      "ask_run_position\030\006 \001(\t\022L\n\017variable_value" +
      "s\030\007 \003(\01323.lh_proto.TaskScheduleRequestPb" +
      ".VariableValuesEntry\032P\n\023VariableValuesEn" +
      "try\022\013\n\003key\030\001 \001(\t\022(\n\005value\030\002 \001(\0132\031.lh_pro" +
      "to.VariableValuePb:\0028\001\"\240\001\n\022TaskStartedEv" +
      "entPb\022\031\n\021thread_run_number\030\001 \001(\005\022\027\n\017task" +
      "_run_number\030\002 \001(\005\022\031\n\021task_run_position\030\003" +
      " \001(\005\022(\n\004time\030\004 \001(\0132\032.google.protobuf.Tim" +
      "estamp\022\021\n\tworker_id\030\005 \001(\t\"\327\001\n\024TaskComple" +
      "tedEventPb\022\031\n\021thread_run_number\030\001 \001(\005\022\027\n" +
      "\017task_run_number\030\002 \001(\005\022\031\n\021task_run_posit" +
      "ion\030\003 \001(\005\022(\n\004time\030\004 \001(\0132\032.google.protobu" +
      "f.Timestamp\022\021\n\tworker_id\030\005 \001(\t\022\016\n\006output" +
      "\030\006 \001(\014\022\022\n\nlog_output\030\007 \001(\014\022\017\n\007success\030\010 " +
      "\001(\010\"\227\002\n\014WFRunEventPb\022\021\n\twf_run_id\030\001 \001(\t\022" +
      "2\n\013run_request\030\002 \001(\0132\030.lh_proto.WFRunReq" +
      "uestPbH\000\210\001\001\0228\n\rstarted_event\030\003 \001(\0132\034.lh_" +
      "proto.TaskStartedEventPbH\001\210\001\001\022<\n\017complet" +
      "ed_event\030\004 \001(\0132\036.lh_proto.TaskCompletedE" +
      "ventPbH\002\210\001\001\022\022\n\nwf_spec_id\030\005 \001(\tB\016\n\014_run_" +
      "requestB\020\n\016_started_eventB\022\n\020_completed_" +
      "event\"\322\001\n\rVariableDefPb\022\n\n\002id\030\001 \001(\t\022.\n\nc" +
      "reated_at\030\002 \001(\0132\032.google.protobuf.Timest" +
      "amp\022.\n\nupdated_at\030\003 \001(\0132\032.google.protobu" +
      "f.Timestamp\022&\n\004type\030\004 \001(\0162\030.lh_proto.Var" +
      "iableTypePb\022\026\n\016thread_spec_id\030\005 \001(\t\022\025\n\rv" +
      "ariable_name\030\006 \001(\t\"t\n\006EdgePb\022\n\n\002id\030\001 \001(\t" +
      "\022.\n\ncreated_at\030\002 \001(\0132\032.google.protobuf.T" +
      "imestamp\022.\n\nupdated_at\030\003 \001(\0132\032.google.pr" +
      "otobuf.Timestamp\"t\n\006NodePb\022\n\n\002id\030\001 \001(\t\022." +
      "\n\ncreated_at\030\002 \001(\0132\032.google.protobuf.Tim" +
      "estamp\022.\n\nupdated_at\030\003 \001(\0132\032.google.prot" +
      "obuf.Timestamp\"\302\002\n\014ThreadSpecPb\022\n\n\002id\030\001 " +
      "\001(\t\022.\n\ncreated_at\030\002 \001(\0132\032.google.protobu" +
      "f.Timestamp\022.\n\nupdated_at\030\003 \001(\0132\032.google" +
      ".protobuf.Timestamp\022\022\n\nwf_spec_id\030\004 \001(\t\022" +
      "\024\n\014wf_spec_name\030\005 \001(\t\022\014\n\004name\030\006 \001(\t\022\037\n\005n" +
      "odes\030\007 \003(\0132\020.lh_proto.NodePb\022\037\n\005edges\030\010 " +
      "\003(\0132\020.lh_proto.EdgePb\022\034\n\024entrypoint_node" +
      "_name\030\t \001(\t\022.\n\rvariable_defs\030\n \003(\0132\027.lh_" +
      "proto.VariableDefPb\"\230\002\n\010WFSpecPb\022\n\n\002id\030\001" +
      " \001(\t\022.\n\ncreated_at\030\002 \001(\0132\032.google.protob" +
      "uf.Timestamp\022.\n\nupdated_at\030\003 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022,\n\014thread_specs\030\004 \003" +
      "(\0132\026.lh_proto.ThreadSpecPb\022\036\n\026entrypoint" +
      "_thread_name\030\005 \001(\t\022$\n\006status\030\006 \001(\0162\024.lh_" +
      "proto.LHStatusPb\022,\n\016desired_status\030\007 \001(\016" +
      "2\024.lh_proto.LHStatusPb*T\n\016VariableTypePb" +
      "\022\n\n\006STRING\020\000\022\007\n\003INT\020\001\022\t\n\005FLOAT\020\002\022\013\n\007BOOL" +
      "EAN\020\003\022\t\n\005ARRAY\020\004\022\n\n\006OBJECT\020\005*Z\n\nLHStatus" +
      "Pb\022\014\n\010STARTING\020\000\022\013\n\007RUNNING\020\001\022\r\n\tCOMPLET" +
      "ED\020\002\022\013\n\007HALTING\020\003\022\n\n\006HALTED\020\004\022\t\n\005ERROR\020\005" +
      "B$\n\024io.littlehorse.protoP\001Z\n.;lh_protob\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_lh_proto_VariableValuePb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lh_proto_VariableValuePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_VariableValuePb_descriptor,
        new java.lang.String[] { "Type", "SerializedValue", });
    internal_static_lh_proto_TaskRunPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lh_proto_TaskRunPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_TaskRunPb_descriptor,
        new java.lang.String[] { "WfRunId", "ThreadRunNumber", "OrderPosition", "Number", "NodeName", "NodeId", "TaskDefId", "WorkerId", "AttemptNumber", "Status", "Stdout", "Stderr", "ReturnCode", "ScheduledTime", "StartedTime", "EndedTime", "WorkerId", "Stdout", "Stderr", "ReturnCode", });
    internal_static_lh_proto_ThreadRunPb_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lh_proto_ThreadRunPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_ThreadRunPb_descriptor,
        new java.lang.String[] { "Variables", "ActiveTaskRuns", "Status", "CurrentNode", "ThreadSpecName", "CurrentNode", });
    internal_static_lh_proto_ThreadRunPb_VariablesEntry_descriptor =
      internal_static_lh_proto_ThreadRunPb_descriptor.getNestedTypes().get(0);
    internal_static_lh_proto_ThreadRunPb_VariablesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_ThreadRunPb_VariablesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lh_proto_WFRunPb_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lh_proto_WFRunPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_WFRunPb_descriptor,
        new java.lang.String[] { "Id", "WfSpecId", "WfSpecName", "StartTime", "EndTime", "Status", "ThreadRuns", "EndTime", });
    internal_static_lh_proto_WFRunRequestPb_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lh_proto_WFRunRequestPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_WFRunRequestPb_descriptor,
        new java.lang.String[] { "WfRunId", "WfSpecId", "VariableValues", });
    internal_static_lh_proto_WFRunRequestPb_VariableValuesEntry_descriptor =
      internal_static_lh_proto_WFRunRequestPb_descriptor.getNestedTypes().get(0);
    internal_static_lh_proto_WFRunRequestPb_VariableValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_WFRunRequestPb_VariableValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lh_proto_TaskScheduleRequestPb_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lh_proto_TaskScheduleRequestPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_TaskScheduleRequestPb_descriptor,
        new java.lang.String[] { "TaskDefId", "TaskDefName", "ThreadRunNumber", "TaskRunNumber", "TaskRunPosition", "VariableValues", });
    internal_static_lh_proto_TaskScheduleRequestPb_VariableValuesEntry_descriptor =
      internal_static_lh_proto_TaskScheduleRequestPb_descriptor.getNestedTypes().get(0);
    internal_static_lh_proto_TaskScheduleRequestPb_VariableValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_TaskScheduleRequestPb_VariableValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lh_proto_TaskStartedEventPb_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_lh_proto_TaskStartedEventPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_TaskStartedEventPb_descriptor,
        new java.lang.String[] { "ThreadRunNumber", "TaskRunNumber", "TaskRunPosition", "Time", "WorkerId", });
    internal_static_lh_proto_TaskCompletedEventPb_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_lh_proto_TaskCompletedEventPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_TaskCompletedEventPb_descriptor,
        new java.lang.String[] { "ThreadRunNumber", "TaskRunNumber", "TaskRunPosition", "Time", "WorkerId", "Output", "LogOutput", "Success", });
    internal_static_lh_proto_WFRunEventPb_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_lh_proto_WFRunEventPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_WFRunEventPb_descriptor,
        new java.lang.String[] { "WfRunId", "RunRequest", "StartedEvent", "CompletedEvent", "WfSpecId", "RunRequest", "StartedEvent", "CompletedEvent", });
    internal_static_lh_proto_VariableDefPb_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_lh_proto_VariableDefPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_VariableDefPb_descriptor,
        new java.lang.String[] { "Id", "CreatedAt", "UpdatedAt", "Type", "ThreadSpecId", "VariableName", });
    internal_static_lh_proto_EdgePb_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_lh_proto_EdgePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_EdgePb_descriptor,
        new java.lang.String[] { "Id", "CreatedAt", "UpdatedAt", });
    internal_static_lh_proto_NodePb_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_lh_proto_NodePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_NodePb_descriptor,
        new java.lang.String[] { "Id", "CreatedAt", "UpdatedAt", });
    internal_static_lh_proto_ThreadSpecPb_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_lh_proto_ThreadSpecPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_ThreadSpecPb_descriptor,
        new java.lang.String[] { "Id", "CreatedAt", "UpdatedAt", "WfSpecId", "WfSpecName", "Name", "Nodes", "Edges", "EntrypointNodeName", "VariableDefs", });
    internal_static_lh_proto_WFSpecPb_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_lh_proto_WFSpecPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lh_proto_WFSpecPb_descriptor,
        new java.lang.String[] { "Id", "CreatedAt", "UpdatedAt", "ThreadSpecs", "EntrypointThreadName", "Status", "DesiredStatus", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
