// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

public interface TaskScheduleRequestPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lh_proto.TaskScheduleRequestPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_def_id = 1;</code>
   * @return The taskDefId.
   */
  java.lang.String getTaskDefId();
  /**
   * <code>string task_def_id = 1;</code>
   * @return The bytes for taskDefId.
   */
  com.google.protobuf.ByteString
      getTaskDefIdBytes();

  /**
   * <code>string task_def_name = 2;</code>
   * @return The taskDefName.
   */
  java.lang.String getTaskDefName();
  /**
   * <code>string task_def_name = 2;</code>
   * @return The bytes for taskDefName.
   */
  com.google.protobuf.ByteString
      getTaskDefNameBytes();

  /**
   * <code>string thread_run_number = 4;</code>
   * @return The threadRunNumber.
   */
  java.lang.String getThreadRunNumber();
  /**
   * <code>string thread_run_number = 4;</code>
   * @return The bytes for threadRunNumber.
   */
  com.google.protobuf.ByteString
      getThreadRunNumberBytes();

  /**
   * <code>string task_run_number = 5;</code>
   * @return The taskRunNumber.
   */
  java.lang.String getTaskRunNumber();
  /**
   * <code>string task_run_number = 5;</code>
   * @return The bytes for taskRunNumber.
   */
  com.google.protobuf.ByteString
      getTaskRunNumberBytes();

  /**
   * <code>string task_run_position = 6;</code>
   * @return The taskRunPosition.
   */
  java.lang.String getTaskRunPosition();
  /**
   * <code>string task_run_position = 6;</code>
   * @return The bytes for taskRunPosition.
   */
  com.google.protobuf.ByteString
      getTaskRunPositionBytes();

  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
   */
  int getVariableValuesCount();
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
   */
  boolean containsVariableValues(
      java.lang.String key);
  /**
   * Use {@link #getVariableValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb>
  getVariableValues();
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
   */
  java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb>
  getVariableValuesMap();
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
   */

  io.littlehorse.proto.VariableValuePb getVariableValuesOrDefault(
      java.lang.String key,
      io.littlehorse.proto.VariableValuePb defaultValue);
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
   */

  io.littlehorse.proto.VariableValuePb getVariableValuesOrThrow(
      java.lang.String key);
}
