// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

/**
 * Protobuf type {@code lh_proto.TaskScheduleRequestPb}
 */
public final class TaskScheduleRequestPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lh_proto.TaskScheduleRequestPb)
    TaskScheduleRequestPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaskScheduleRequestPb.newBuilder() to construct.
  private TaskScheduleRequestPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskScheduleRequestPb() {
    taskDefId_ = "";
    taskDefName_ = "";
    threadRunNumber_ = "";
    taskRunNumber_ = "";
    taskRunPosition_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TaskScheduleRequestPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TaskScheduleRequestPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            taskDefId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            taskDefName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            threadRunNumber_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            taskRunNumber_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            taskRunPosition_ = s;
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              variableValues_ = com.google.protobuf.MapField.newMapField(
                  VariableValuesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.proto.VariableValuePb>
            variableValues__ = input.readMessage(
                VariableValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            variableValues_.getMutableMap().put(
                variableValues__.getKey(), variableValues__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_TaskScheduleRequestPb_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 7:
        return internalGetVariableValues();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_TaskScheduleRequestPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.proto.TaskScheduleRequestPb.class, io.littlehorse.proto.TaskScheduleRequestPb.Builder.class);
  }

  public static final int TASK_DEF_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object taskDefId_;
  /**
   * <code>string task_def_id = 1;</code>
   * @return The taskDefId.
   */
  @java.lang.Override
  public java.lang.String getTaskDefId() {
    java.lang.Object ref = taskDefId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskDefId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_def_id = 1;</code>
   * @return The bytes for taskDefId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskDefIdBytes() {
    java.lang.Object ref = taskDefId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskDefId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_DEF_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object taskDefName_;
  /**
   * <code>string task_def_name = 2;</code>
   * @return The taskDefName.
   */
  @java.lang.Override
  public java.lang.String getTaskDefName() {
    java.lang.Object ref = taskDefName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskDefName_ = s;
      return s;
    }
  }
  /**
   * <code>string task_def_name = 2;</code>
   * @return The bytes for taskDefName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskDefNameBytes() {
    java.lang.Object ref = taskDefName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskDefName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THREAD_RUN_NUMBER_FIELD_NUMBER = 4;
  private volatile java.lang.Object threadRunNumber_;
  /**
   * <code>string thread_run_number = 4;</code>
   * @return The threadRunNumber.
   */
  @java.lang.Override
  public java.lang.String getThreadRunNumber() {
    java.lang.Object ref = threadRunNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      threadRunNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string thread_run_number = 4;</code>
   * @return The bytes for threadRunNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreadRunNumberBytes() {
    java.lang.Object ref = threadRunNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      threadRunNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_RUN_NUMBER_FIELD_NUMBER = 5;
  private volatile java.lang.Object taskRunNumber_;
  /**
   * <code>string task_run_number = 5;</code>
   * @return The taskRunNumber.
   */
  @java.lang.Override
  public java.lang.String getTaskRunNumber() {
    java.lang.Object ref = taskRunNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskRunNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string task_run_number = 5;</code>
   * @return The bytes for taskRunNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskRunNumberBytes() {
    java.lang.Object ref = taskRunNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskRunNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_RUN_POSITION_FIELD_NUMBER = 6;
  private volatile java.lang.Object taskRunPosition_;
  /**
   * <code>string task_run_position = 6;</code>
   * @return The taskRunPosition.
   */
  @java.lang.Override
  public java.lang.String getTaskRunPosition() {
    java.lang.Object ref = taskRunPosition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskRunPosition_ = s;
      return s;
    }
  }
  /**
   * <code>string task_run_position = 6;</code>
   * @return The bytes for taskRunPosition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskRunPositionBytes() {
    java.lang.Object ref = taskRunPosition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskRunPosition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VARIABLE_VALUES_FIELD_NUMBER = 7;
  private static final class VariableValuesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.littlehorse.proto.VariableValuePb> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.littlehorse.proto.VariableValuePb>newDefaultInstance(
                io.littlehorse.proto.LhProto.internal_static_lh_proto_TaskScheduleRequestPb_VariableValuesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.littlehorse.proto.VariableValuePb.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, io.littlehorse.proto.VariableValuePb> variableValues_;
  private com.google.protobuf.MapField<java.lang.String, io.littlehorse.proto.VariableValuePb>
  internalGetVariableValues() {
    if (variableValues_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          VariableValuesDefaultEntryHolder.defaultEntry);
    }
    return variableValues_;
  }

  public int getVariableValuesCount() {
    return internalGetVariableValues().getMap().size();
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
   */

  @java.lang.Override
  public boolean containsVariableValues(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetVariableValues().getMap().containsKey(key);
  }
  /**
   * Use {@link #getVariableValuesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariableValues() {
    return getVariableValuesMap();
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariableValuesMap() {
    return internalGetVariableValues().getMap();
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
   */
  @java.lang.Override

  public io.littlehorse.proto.VariableValuePb getVariableValuesOrDefault(
      java.lang.String key,
      io.littlehorse.proto.VariableValuePb defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
        internalGetVariableValues().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
   */
  @java.lang.Override

  public io.littlehorse.proto.VariableValuePb getVariableValuesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
        internalGetVariableValues().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTaskDefIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskDefId_);
    }
    if (!getTaskDefNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskDefName_);
    }
    if (!getThreadRunNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, threadRunNumber_);
    }
    if (!getTaskRunNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, taskRunNumber_);
    }
    if (!getTaskRunPositionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, taskRunPosition_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetVariableValues(),
        VariableValuesDefaultEntryHolder.defaultEntry,
        7);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTaskDefIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskDefId_);
    }
    if (!getTaskDefNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskDefName_);
    }
    if (!getThreadRunNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, threadRunNumber_);
    }
    if (!getTaskRunNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, taskRunNumber_);
    }
    if (!getTaskRunPositionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, taskRunPosition_);
    }
    for (java.util.Map.Entry<java.lang.String, io.littlehorse.proto.VariableValuePb> entry
         : internalGetVariableValues().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.proto.VariableValuePb>
      variableValues__ = VariableValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, variableValues__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.proto.TaskScheduleRequestPb)) {
      return super.equals(obj);
    }
    io.littlehorse.proto.TaskScheduleRequestPb other = (io.littlehorse.proto.TaskScheduleRequestPb) obj;

    if (!getTaskDefId()
        .equals(other.getTaskDefId())) return false;
    if (!getTaskDefName()
        .equals(other.getTaskDefName())) return false;
    if (!getThreadRunNumber()
        .equals(other.getThreadRunNumber())) return false;
    if (!getTaskRunNumber()
        .equals(other.getTaskRunNumber())) return false;
    if (!getTaskRunPosition()
        .equals(other.getTaskRunPosition())) return false;
    if (!internalGetVariableValues().equals(
        other.internalGetVariableValues())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASK_DEF_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskDefId().hashCode();
    hash = (37 * hash) + TASK_DEF_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTaskDefName().hashCode();
    hash = (37 * hash) + THREAD_RUN_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getThreadRunNumber().hashCode();
    hash = (37 * hash) + TASK_RUN_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getTaskRunNumber().hashCode();
    hash = (37 * hash) + TASK_RUN_POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getTaskRunPosition().hashCode();
    if (!internalGetVariableValues().getMap().isEmpty()) {
      hash = (37 * hash) + VARIABLE_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetVariableValues().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.TaskScheduleRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.proto.TaskScheduleRequestPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lh_proto.TaskScheduleRequestPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lh_proto.TaskScheduleRequestPb)
      io.littlehorse.proto.TaskScheduleRequestPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_TaskScheduleRequestPb_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetVariableValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableVariableValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_TaskScheduleRequestPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.proto.TaskScheduleRequestPb.class, io.littlehorse.proto.TaskScheduleRequestPb.Builder.class);
    }

    // Construct using io.littlehorse.proto.TaskScheduleRequestPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      taskDefId_ = "";

      taskDefName_ = "";

      threadRunNumber_ = "";

      taskRunNumber_ = "";

      taskRunPosition_ = "";

      internalGetMutableVariableValues().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_TaskScheduleRequestPb_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.proto.TaskScheduleRequestPb getDefaultInstanceForType() {
      return io.littlehorse.proto.TaskScheduleRequestPb.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.proto.TaskScheduleRequestPb build() {
      io.littlehorse.proto.TaskScheduleRequestPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.proto.TaskScheduleRequestPb buildPartial() {
      io.littlehorse.proto.TaskScheduleRequestPb result = new io.littlehorse.proto.TaskScheduleRequestPb(this);
      int from_bitField0_ = bitField0_;
      result.taskDefId_ = taskDefId_;
      result.taskDefName_ = taskDefName_;
      result.threadRunNumber_ = threadRunNumber_;
      result.taskRunNumber_ = taskRunNumber_;
      result.taskRunPosition_ = taskRunPosition_;
      result.variableValues_ = internalGetVariableValues();
      result.variableValues_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.proto.TaskScheduleRequestPb) {
        return mergeFrom((io.littlehorse.proto.TaskScheduleRequestPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.proto.TaskScheduleRequestPb other) {
      if (other == io.littlehorse.proto.TaskScheduleRequestPb.getDefaultInstance()) return this;
      if (!other.getTaskDefId().isEmpty()) {
        taskDefId_ = other.taskDefId_;
        onChanged();
      }
      if (!other.getTaskDefName().isEmpty()) {
        taskDefName_ = other.taskDefName_;
        onChanged();
      }
      if (!other.getThreadRunNumber().isEmpty()) {
        threadRunNumber_ = other.threadRunNumber_;
        onChanged();
      }
      if (!other.getTaskRunNumber().isEmpty()) {
        taskRunNumber_ = other.taskRunNumber_;
        onChanged();
      }
      if (!other.getTaskRunPosition().isEmpty()) {
        taskRunPosition_ = other.taskRunPosition_;
        onChanged();
      }
      internalGetMutableVariableValues().mergeFrom(
          other.internalGetVariableValues());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.littlehorse.proto.TaskScheduleRequestPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.littlehorse.proto.TaskScheduleRequestPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object taskDefId_ = "";
    /**
     * <code>string task_def_id = 1;</code>
     * @return The taskDefId.
     */
    public java.lang.String getTaskDefId() {
      java.lang.Object ref = taskDefId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskDefId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_def_id = 1;</code>
     * @return The bytes for taskDefId.
     */
    public com.google.protobuf.ByteString
        getTaskDefIdBytes() {
      java.lang.Object ref = taskDefId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskDefId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_def_id = 1;</code>
     * @param value The taskDefId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskDefId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskDefId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string task_def_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskDefId() {
      
      taskDefId_ = getDefaultInstance().getTaskDefId();
      onChanged();
      return this;
    }
    /**
     * <code>string task_def_id = 1;</code>
     * @param value The bytes for taskDefId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskDefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskDefId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taskDefName_ = "";
    /**
     * <code>string task_def_name = 2;</code>
     * @return The taskDefName.
     */
    public java.lang.String getTaskDefName() {
      java.lang.Object ref = taskDefName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskDefName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_def_name = 2;</code>
     * @return The bytes for taskDefName.
     */
    public com.google.protobuf.ByteString
        getTaskDefNameBytes() {
      java.lang.Object ref = taskDefName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskDefName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_def_name = 2;</code>
     * @param value The taskDefName to set.
     * @return This builder for chaining.
     */
    public Builder setTaskDefName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskDefName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string task_def_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskDefName() {
      
      taskDefName_ = getDefaultInstance().getTaskDefName();
      onChanged();
      return this;
    }
    /**
     * <code>string task_def_name = 2;</code>
     * @param value The bytes for taskDefName to set.
     * @return This builder for chaining.
     */
    public Builder setTaskDefNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskDefName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object threadRunNumber_ = "";
    /**
     * <code>string thread_run_number = 4;</code>
     * @return The threadRunNumber.
     */
    public java.lang.String getThreadRunNumber() {
      java.lang.Object ref = threadRunNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        threadRunNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string thread_run_number = 4;</code>
     * @return The bytes for threadRunNumber.
     */
    public com.google.protobuf.ByteString
        getThreadRunNumberBytes() {
      java.lang.Object ref = threadRunNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        threadRunNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string thread_run_number = 4;</code>
     * @param value The threadRunNumber to set.
     * @return This builder for chaining.
     */
    public Builder setThreadRunNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      threadRunNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string thread_run_number = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadRunNumber() {
      
      threadRunNumber_ = getDefaultInstance().getThreadRunNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string thread_run_number = 4;</code>
     * @param value The bytes for threadRunNumber to set.
     * @return This builder for chaining.
     */
    public Builder setThreadRunNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      threadRunNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taskRunNumber_ = "";
    /**
     * <code>string task_run_number = 5;</code>
     * @return The taskRunNumber.
     */
    public java.lang.String getTaskRunNumber() {
      java.lang.Object ref = taskRunNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskRunNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_run_number = 5;</code>
     * @return The bytes for taskRunNumber.
     */
    public com.google.protobuf.ByteString
        getTaskRunNumberBytes() {
      java.lang.Object ref = taskRunNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskRunNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_run_number = 5;</code>
     * @param value The taskRunNumber to set.
     * @return This builder for chaining.
     */
    public Builder setTaskRunNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskRunNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string task_run_number = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskRunNumber() {
      
      taskRunNumber_ = getDefaultInstance().getTaskRunNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string task_run_number = 5;</code>
     * @param value The bytes for taskRunNumber to set.
     * @return This builder for chaining.
     */
    public Builder setTaskRunNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskRunNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taskRunPosition_ = "";
    /**
     * <code>string task_run_position = 6;</code>
     * @return The taskRunPosition.
     */
    public java.lang.String getTaskRunPosition() {
      java.lang.Object ref = taskRunPosition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskRunPosition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_run_position = 6;</code>
     * @return The bytes for taskRunPosition.
     */
    public com.google.protobuf.ByteString
        getTaskRunPositionBytes() {
      java.lang.Object ref = taskRunPosition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskRunPosition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_run_position = 6;</code>
     * @param value The taskRunPosition to set.
     * @return This builder for chaining.
     */
    public Builder setTaskRunPosition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskRunPosition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string task_run_position = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskRunPosition() {
      
      taskRunPosition_ = getDefaultInstance().getTaskRunPosition();
      onChanged();
      return this;
    }
    /**
     * <code>string task_run_position = 6;</code>
     * @param value The bytes for taskRunPosition to set.
     * @return This builder for chaining.
     */
    public Builder setTaskRunPositionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskRunPosition_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, io.littlehorse.proto.VariableValuePb> variableValues_;
    private com.google.protobuf.MapField<java.lang.String, io.littlehorse.proto.VariableValuePb>
    internalGetVariableValues() {
      if (variableValues_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            VariableValuesDefaultEntryHolder.defaultEntry);
      }
      return variableValues_;
    }
    private com.google.protobuf.MapField<java.lang.String, io.littlehorse.proto.VariableValuePb>
    internalGetMutableVariableValues() {
      onChanged();;
      if (variableValues_ == null) {
        variableValues_ = com.google.protobuf.MapField.newMapField(
            VariableValuesDefaultEntryHolder.defaultEntry);
      }
      if (!variableValues_.isMutable()) {
        variableValues_ = variableValues_.copy();
      }
      return variableValues_;
    }

    public int getVariableValuesCount() {
      return internalGetVariableValues().getMap().size();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
     */

    @java.lang.Override
    public boolean containsVariableValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetVariableValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getVariableValuesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariableValues() {
      return getVariableValuesMap();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariableValuesMap() {
      return internalGetVariableValues().getMap();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
     */
    @java.lang.Override

    public io.littlehorse.proto.VariableValuePb getVariableValuesOrDefault(
        java.lang.String key,
        io.littlehorse.proto.VariableValuePb defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
          internalGetVariableValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
     */
    @java.lang.Override

    public io.littlehorse.proto.VariableValuePb getVariableValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
          internalGetVariableValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearVariableValues() {
      internalGetMutableVariableValues().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
     */

    public Builder removeVariableValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableVariableValues().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb>
    getMutableVariableValues() {
      return internalGetMutableVariableValues().getMutableMap();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
     */
    public Builder putVariableValues(
        java.lang.String key,
        io.littlehorse.proto.VariableValuePb value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableVariableValues().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 7;</code>
     */

    public Builder putAllVariableValues(
        java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> values) {
      internalGetMutableVariableValues().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lh_proto.TaskScheduleRequestPb)
  }

  // @@protoc_insertion_point(class_scope:lh_proto.TaskScheduleRequestPb)
  private static final io.littlehorse.proto.TaskScheduleRequestPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.proto.TaskScheduleRequestPb();
  }

  public static io.littlehorse.proto.TaskScheduleRequestPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskScheduleRequestPb>
      PARSER = new com.google.protobuf.AbstractParser<TaskScheduleRequestPb>() {
    @java.lang.Override
    public TaskScheduleRequestPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TaskScheduleRequestPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaskScheduleRequestPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskScheduleRequestPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.proto.TaskScheduleRequestPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

