// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

/**
 * Protobuf type {@code lh_proto.ThreadRunPb}
 */
public final class ThreadRunPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lh_proto.ThreadRunPb)
    ThreadRunPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ThreadRunPb.newBuilder() to construct.
  private ThreadRunPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ThreadRunPb() {
    status_ = 0;
    currentNode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ThreadRunPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ThreadRunPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              variables_ = com.google.protobuf.MapField.newMapField(
                  VariablesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.proto.VariableValuePb>
            variables__ = input.readMessage(
                VariablesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            variables_.getMutableMap().put(
                variables__.getKey(), variables__.getValue());
            break;
          }
          case 18: {
            io.littlehorse.proto.TaskRunPb.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = currentTaskRun_.toBuilder();
            }
            currentTaskRun_ = input.readMessage(io.littlehorse.proto.TaskRunPb.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currentTaskRun_);
              currentTaskRun_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            currentNode_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadRunPb_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetVariables();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadRunPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.proto.ThreadRunPb.class, io.littlehorse.proto.ThreadRunPb.Builder.class);
  }

  private int bitField0_;
  public static final int VARIABLES_FIELD_NUMBER = 1;
  private static final class VariablesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.littlehorse.proto.VariableValuePb> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.littlehorse.proto.VariableValuePb>newDefaultInstance(
                io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadRunPb_VariablesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.littlehorse.proto.VariableValuePb.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, io.littlehorse.proto.VariableValuePb> variables_;
  private com.google.protobuf.MapField<java.lang.String, io.littlehorse.proto.VariableValuePb>
  internalGetVariables() {
    if (variables_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          VariablesDefaultEntryHolder.defaultEntry);
    }
    return variables_;
  }

  public int getVariablesCount() {
    return internalGetVariables().getMap().size();
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
   */

  @java.lang.Override
  public boolean containsVariables(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetVariables().getMap().containsKey(key);
  }
  /**
   * Use {@link #getVariablesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariables() {
    return getVariablesMap();
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariablesMap() {
    return internalGetVariables().getMap();
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
   */
  @java.lang.Override

  public io.littlehorse.proto.VariableValuePb getVariablesOrDefault(
      java.lang.String key,
      io.littlehorse.proto.VariableValuePb defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
        internalGetVariables().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
   */
  @java.lang.Override

  public io.littlehorse.proto.VariableValuePb getVariablesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
        internalGetVariables().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CURRENT_TASK_RUN_FIELD_NUMBER = 2;
  private io.littlehorse.proto.TaskRunPb currentTaskRun_;
  /**
   * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
   * @return Whether the currentTaskRun field is set.
   */
  @java.lang.Override
  public boolean hasCurrentTaskRun() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
   * @return The currentTaskRun.
   */
  @java.lang.Override
  public io.littlehorse.proto.TaskRunPb getCurrentTaskRun() {
    return currentTaskRun_ == null ? io.littlehorse.proto.TaskRunPb.getDefaultInstance() : currentTaskRun_;
  }
  /**
   * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.TaskRunPbOrBuilder getCurrentTaskRunOrBuilder() {
    return currentTaskRun_ == null ? io.littlehorse.proto.TaskRunPb.getDefaultInstance() : currentTaskRun_;
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_;
  /**
   * <code>.lh_proto.LHStatusPb status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.lh_proto.LHStatusPb status = 3;</code>
   * @return The status.
   */
  @java.lang.Override public io.littlehorse.proto.LHStatusPb getStatus() {
    @SuppressWarnings("deprecation")
    io.littlehorse.proto.LHStatusPb result = io.littlehorse.proto.LHStatusPb.valueOf(status_);
    return result == null ? io.littlehorse.proto.LHStatusPb.UNRECOGNIZED : result;
  }

  public static final int CURRENT_NODE_FIELD_NUMBER = 4;
  private volatile java.lang.Object currentNode_;
  /**
   * <code>string current_node = 4;</code>
   * @return Whether the currentNode field is set.
   */
  @java.lang.Override
  public boolean hasCurrentNode() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>string current_node = 4;</code>
   * @return The currentNode.
   */
  @java.lang.Override
  public java.lang.String getCurrentNode() {
    java.lang.Object ref = currentNode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentNode_ = s;
      return s;
    }
  }
  /**
   * <code>string current_node = 4;</code>
   * @return The bytes for currentNode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrentNodeBytes() {
    java.lang.Object ref = currentNode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentNode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetVariables(),
        VariablesDefaultEntryHolder.defaultEntry,
        1);
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getCurrentTaskRun());
    }
    if (status_ != io.littlehorse.proto.LHStatusPb.STARTING.getNumber()) {
      output.writeEnum(3, status_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, currentNode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, io.littlehorse.proto.VariableValuePb> entry
         : internalGetVariables().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.proto.VariableValuePb>
      variables__ = VariablesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, variables__);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCurrentTaskRun());
    }
    if (status_ != io.littlehorse.proto.LHStatusPb.STARTING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, currentNode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.proto.ThreadRunPb)) {
      return super.equals(obj);
    }
    io.littlehorse.proto.ThreadRunPb other = (io.littlehorse.proto.ThreadRunPb) obj;

    if (!internalGetVariables().equals(
        other.internalGetVariables())) return false;
    if (hasCurrentTaskRun() != other.hasCurrentTaskRun()) return false;
    if (hasCurrentTaskRun()) {
      if (!getCurrentTaskRun()
          .equals(other.getCurrentTaskRun())) return false;
    }
    if (status_ != other.status_) return false;
    if (hasCurrentNode() != other.hasCurrentNode()) return false;
    if (hasCurrentNode()) {
      if (!getCurrentNode()
          .equals(other.getCurrentNode())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetVariables().getMap().isEmpty()) {
      hash = (37 * hash) + VARIABLES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetVariables().hashCode();
    }
    if (hasCurrentTaskRun()) {
      hash = (37 * hash) + CURRENT_TASK_RUN_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentTaskRun().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasCurrentNode()) {
      hash = (37 * hash) + CURRENT_NODE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentNode().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.proto.ThreadRunPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.ThreadRunPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadRunPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.ThreadRunPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadRunPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.ThreadRunPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadRunPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.ThreadRunPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadRunPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.ThreadRunPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadRunPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.ThreadRunPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.proto.ThreadRunPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lh_proto.ThreadRunPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lh_proto.ThreadRunPb)
      io.littlehorse.proto.ThreadRunPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadRunPb_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetVariables();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableVariables();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadRunPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.proto.ThreadRunPb.class, io.littlehorse.proto.ThreadRunPb.Builder.class);
    }

    // Construct using io.littlehorse.proto.ThreadRunPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCurrentTaskRunFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableVariables().clear();
      if (currentTaskRunBuilder_ == null) {
        currentTaskRun_ = null;
      } else {
        currentTaskRunBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = 0;

      currentNode_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadRunPb_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.proto.ThreadRunPb getDefaultInstanceForType() {
      return io.littlehorse.proto.ThreadRunPb.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.proto.ThreadRunPb build() {
      io.littlehorse.proto.ThreadRunPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.proto.ThreadRunPb buildPartial() {
      io.littlehorse.proto.ThreadRunPb result = new io.littlehorse.proto.ThreadRunPb(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.variables_ = internalGetVariables();
      result.variables_.makeImmutable();
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (currentTaskRunBuilder_ == null) {
          result.currentTaskRun_ = currentTaskRun_;
        } else {
          result.currentTaskRun_ = currentTaskRunBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.currentNode_ = currentNode_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.proto.ThreadRunPb) {
        return mergeFrom((io.littlehorse.proto.ThreadRunPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.proto.ThreadRunPb other) {
      if (other == io.littlehorse.proto.ThreadRunPb.getDefaultInstance()) return this;
      internalGetMutableVariables().mergeFrom(
          other.internalGetVariables());
      if (other.hasCurrentTaskRun()) {
        mergeCurrentTaskRun(other.getCurrentTaskRun());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasCurrentNode()) {
        bitField0_ |= 0x00000004;
        currentNode_ = other.currentNode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.littlehorse.proto.ThreadRunPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.littlehorse.proto.ThreadRunPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, io.littlehorse.proto.VariableValuePb> variables_;
    private com.google.protobuf.MapField<java.lang.String, io.littlehorse.proto.VariableValuePb>
    internalGetVariables() {
      if (variables_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            VariablesDefaultEntryHolder.defaultEntry);
      }
      return variables_;
    }
    private com.google.protobuf.MapField<java.lang.String, io.littlehorse.proto.VariableValuePb>
    internalGetMutableVariables() {
      onChanged();;
      if (variables_ == null) {
        variables_ = com.google.protobuf.MapField.newMapField(
            VariablesDefaultEntryHolder.defaultEntry);
      }
      if (!variables_.isMutable()) {
        variables_ = variables_.copy();
      }
      return variables_;
    }

    public int getVariablesCount() {
      return internalGetVariables().getMap().size();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
     */

    @java.lang.Override
    public boolean containsVariables(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetVariables().getMap().containsKey(key);
    }
    /**
     * Use {@link #getVariablesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariables() {
      return getVariablesMap();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariablesMap() {
      return internalGetVariables().getMap();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
     */
    @java.lang.Override

    public io.littlehorse.proto.VariableValuePb getVariablesOrDefault(
        java.lang.String key,
        io.littlehorse.proto.VariableValuePb defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
          internalGetVariables().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
     */
    @java.lang.Override

    public io.littlehorse.proto.VariableValuePb getVariablesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
          internalGetVariables().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearVariables() {
      internalGetMutableVariables().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
     */

    public Builder removeVariables(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableVariables().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb>
    getMutableVariables() {
      return internalGetMutableVariables().getMutableMap();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
     */
    public Builder putVariables(
        java.lang.String key,
        io.littlehorse.proto.VariableValuePb value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableVariables().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
     */

    public Builder putAllVariables(
        java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> values) {
      internalGetMutableVariables().getMutableMap()
          .putAll(values);
      return this;
    }

    private io.littlehorse.proto.TaskRunPb currentTaskRun_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.proto.TaskRunPb, io.littlehorse.proto.TaskRunPb.Builder, io.littlehorse.proto.TaskRunPbOrBuilder> currentTaskRunBuilder_;
    /**
     * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
     * @return Whether the currentTaskRun field is set.
     */
    public boolean hasCurrentTaskRun() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
     * @return The currentTaskRun.
     */
    public io.littlehorse.proto.TaskRunPb getCurrentTaskRun() {
      if (currentTaskRunBuilder_ == null) {
        return currentTaskRun_ == null ? io.littlehorse.proto.TaskRunPb.getDefaultInstance() : currentTaskRun_;
      } else {
        return currentTaskRunBuilder_.getMessage();
      }
    }
    /**
     * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
     */
    public Builder setCurrentTaskRun(io.littlehorse.proto.TaskRunPb value) {
      if (currentTaskRunBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentTaskRun_ = value;
        onChanged();
      } else {
        currentTaskRunBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
     */
    public Builder setCurrentTaskRun(
        io.littlehorse.proto.TaskRunPb.Builder builderForValue) {
      if (currentTaskRunBuilder_ == null) {
        currentTaskRun_ = builderForValue.build();
        onChanged();
      } else {
        currentTaskRunBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
     */
    public Builder mergeCurrentTaskRun(io.littlehorse.proto.TaskRunPb value) {
      if (currentTaskRunBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            currentTaskRun_ != null &&
            currentTaskRun_ != io.littlehorse.proto.TaskRunPb.getDefaultInstance()) {
          currentTaskRun_ =
            io.littlehorse.proto.TaskRunPb.newBuilder(currentTaskRun_).mergeFrom(value).buildPartial();
        } else {
          currentTaskRun_ = value;
        }
        onChanged();
      } else {
        currentTaskRunBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
     */
    public Builder clearCurrentTaskRun() {
      if (currentTaskRunBuilder_ == null) {
        currentTaskRun_ = null;
        onChanged();
      } else {
        currentTaskRunBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
     */
    public io.littlehorse.proto.TaskRunPb.Builder getCurrentTaskRunBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCurrentTaskRunFieldBuilder().getBuilder();
    }
    /**
     * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
     */
    public io.littlehorse.proto.TaskRunPbOrBuilder getCurrentTaskRunOrBuilder() {
      if (currentTaskRunBuilder_ != null) {
        return currentTaskRunBuilder_.getMessageOrBuilder();
      } else {
        return currentTaskRun_ == null ?
            io.littlehorse.proto.TaskRunPb.getDefaultInstance() : currentTaskRun_;
      }
    }
    /**
     * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.proto.TaskRunPb, io.littlehorse.proto.TaskRunPb.Builder, io.littlehorse.proto.TaskRunPbOrBuilder> 
        getCurrentTaskRunFieldBuilder() {
      if (currentTaskRunBuilder_ == null) {
        currentTaskRunBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.proto.TaskRunPb, io.littlehorse.proto.TaskRunPb.Builder, io.littlehorse.proto.TaskRunPbOrBuilder>(
                getCurrentTaskRun(),
                getParentForChildren(),
                isClean());
        currentTaskRun_ = null;
      }
      return currentTaskRunBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.lh_proto.LHStatusPb status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.lh_proto.LHStatusPb status = 3;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.lh_proto.LHStatusPb status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public io.littlehorse.proto.LHStatusPb getStatus() {
      @SuppressWarnings("deprecation")
      io.littlehorse.proto.LHStatusPb result = io.littlehorse.proto.LHStatusPb.valueOf(status_);
      return result == null ? io.littlehorse.proto.LHStatusPb.UNRECOGNIZED : result;
    }
    /**
     * <code>.lh_proto.LHStatusPb status = 3;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(io.littlehorse.proto.LHStatusPb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.lh_proto.LHStatusPb status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object currentNode_ = "";
    /**
     * <code>string current_node = 4;</code>
     * @return Whether the currentNode field is set.
     */
    public boolean hasCurrentNode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>string current_node = 4;</code>
     * @return The currentNode.
     */
    public java.lang.String getCurrentNode() {
      java.lang.Object ref = currentNode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentNode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string current_node = 4;</code>
     * @return The bytes for currentNode.
     */
    public com.google.protobuf.ByteString
        getCurrentNodeBytes() {
      java.lang.Object ref = currentNode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentNode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string current_node = 4;</code>
     * @param value The currentNode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentNode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      currentNode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string current_node = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentNode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      currentNode_ = getDefaultInstance().getCurrentNode();
      onChanged();
      return this;
    }
    /**
     * <code>string current_node = 4;</code>
     * @param value The bytes for currentNode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentNodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      currentNode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lh_proto.ThreadRunPb)
  }

  // @@protoc_insertion_point(class_scope:lh_proto.ThreadRunPb)
  private static final io.littlehorse.proto.ThreadRunPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.proto.ThreadRunPb();
  }

  public static io.littlehorse.proto.ThreadRunPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ThreadRunPb>
      PARSER = new com.google.protobuf.AbstractParser<ThreadRunPb>() {
    @java.lang.Override
    public ThreadRunPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ThreadRunPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ThreadRunPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ThreadRunPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.proto.ThreadRunPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

