// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

/**
 * Protobuf type {@code lh_proto.ThreadSpecPb}
 */
public final class ThreadSpecPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lh_proto.ThreadSpecPb)
    ThreadSpecPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ThreadSpecPb.newBuilder() to construct.
  private ThreadSpecPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ThreadSpecPb() {
    id_ = "";
    wfSpecId_ = "";
    wfSpecName_ = "";
    name_ = "";
    nodes_ = java.util.Collections.emptyList();
    edges_ = java.util.Collections.emptyList();
    entrypointNodeName_ = "";
    variableDefs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ThreadSpecPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ThreadSpecPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdAt_ != null) {
              subBuilder = createdAt_.toBuilder();
            }
            createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdAt_);
              createdAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (updatedAt_ != null) {
              subBuilder = updatedAt_.toBuilder();
            }
            updatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(updatedAt_);
              updatedAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            wfSpecId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            wfSpecName_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              nodes_ = new java.util.ArrayList<io.littlehorse.proto.NodePb>();
              mutable_bitField0_ |= 0x00000001;
            }
            nodes_.add(
                input.readMessage(io.littlehorse.proto.NodePb.parser(), extensionRegistry));
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              edges_ = new java.util.ArrayList<io.littlehorse.proto.EdgePb>();
              mutable_bitField0_ |= 0x00000002;
            }
            edges_.add(
                input.readMessage(io.littlehorse.proto.EdgePb.parser(), extensionRegistry));
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            entrypointNodeName_ = s;
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              variableDefs_ = new java.util.ArrayList<io.littlehorse.proto.VariableDefPb>();
              mutable_bitField0_ |= 0x00000004;
            }
            variableDefs_.add(
                input.readMessage(io.littlehorse.proto.VariableDefPb.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        nodes_ = java.util.Collections.unmodifiableList(nodes_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        edges_ = java.util.Collections.unmodifiableList(edges_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        variableDefs_ = java.util.Collections.unmodifiableList(variableDefs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadSpecPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadSpecPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.proto.ThreadSpecPb.class, io.littlehorse.proto.ThreadSpecPb.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return getCreatedAt();
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return Whether the updatedAt field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedAt() {
    return updatedAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return getUpdatedAt();
  }

  public static final int WF_SPEC_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object wfSpecId_;
  /**
   * <code>string wf_spec_id = 4;</code>
   * @return The wfSpecId.
   */
  @java.lang.Override
  public java.lang.String getWfSpecId() {
    java.lang.Object ref = wfSpecId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wfSpecId_ = s;
      return s;
    }
  }
  /**
   * <code>string wf_spec_id = 4;</code>
   * @return The bytes for wfSpecId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWfSpecIdBytes() {
    java.lang.Object ref = wfSpecId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wfSpecId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WF_SPEC_NAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object wfSpecName_;
  /**
   * <code>string wf_spec_name = 5;</code>
   * @return The wfSpecName.
   */
  @java.lang.Override
  public java.lang.String getWfSpecName() {
    java.lang.Object ref = wfSpecName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wfSpecName_ = s;
      return s;
    }
  }
  /**
   * <code>string wf_spec_name = 5;</code>
   * @return The bytes for wfSpecName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWfSpecNameBytes() {
    java.lang.Object ref = wfSpecName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wfSpecName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 6;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODES_FIELD_NUMBER = 7;
  private java.util.List<io.littlehorse.proto.NodePb> nodes_;
  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  @java.lang.Override
  public java.util.List<io.littlehorse.proto.NodePb> getNodesList() {
    return nodes_;
  }
  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.littlehorse.proto.NodePbOrBuilder> 
      getNodesOrBuilderList() {
    return nodes_;
  }
  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  @java.lang.Override
  public int getNodesCount() {
    return nodes_.size();
  }
  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.NodePb getNodes(int index) {
    return nodes_.get(index);
  }
  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.NodePbOrBuilder getNodesOrBuilder(
      int index) {
    return nodes_.get(index);
  }

  public static final int EDGES_FIELD_NUMBER = 8;
  private java.util.List<io.littlehorse.proto.EdgePb> edges_;
  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  @java.lang.Override
  public java.util.List<io.littlehorse.proto.EdgePb> getEdgesList() {
    return edges_;
  }
  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.littlehorse.proto.EdgePbOrBuilder> 
      getEdgesOrBuilderList() {
    return edges_;
  }
  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  @java.lang.Override
  public int getEdgesCount() {
    return edges_.size();
  }
  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.EdgePb getEdges(int index) {
    return edges_.get(index);
  }
  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.EdgePbOrBuilder getEdgesOrBuilder(
      int index) {
    return edges_.get(index);
  }

  public static final int ENTRYPOINT_NODE_NAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object entrypointNodeName_;
  /**
   * <code>string entrypoint_node_name = 9;</code>
   * @return The entrypointNodeName.
   */
  @java.lang.Override
  public java.lang.String getEntrypointNodeName() {
    java.lang.Object ref = entrypointNodeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entrypointNodeName_ = s;
      return s;
    }
  }
  /**
   * <code>string entrypoint_node_name = 9;</code>
   * @return The bytes for entrypointNodeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntrypointNodeNameBytes() {
    java.lang.Object ref = entrypointNodeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entrypointNodeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VARIABLE_DEFS_FIELD_NUMBER = 10;
  private java.util.List<io.littlehorse.proto.VariableDefPb> variableDefs_;
  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  @java.lang.Override
  public java.util.List<io.littlehorse.proto.VariableDefPb> getVariableDefsList() {
    return variableDefs_;
  }
  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.littlehorse.proto.VariableDefPbOrBuilder> 
      getVariableDefsOrBuilderList() {
    return variableDefs_;
  }
  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  @java.lang.Override
  public int getVariableDefsCount() {
    return variableDefs_.size();
  }
  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.VariableDefPb getVariableDefs(int index) {
    return variableDefs_.get(index);
  }
  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.VariableDefPbOrBuilder getVariableDefsOrBuilder(
      int index) {
    return variableDefs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (createdAt_ != null) {
      output.writeMessage(2, getCreatedAt());
    }
    if (updatedAt_ != null) {
      output.writeMessage(3, getUpdatedAt());
    }
    if (!getWfSpecIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, wfSpecId_);
    }
    if (!getWfSpecNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, wfSpecName_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
    }
    for (int i = 0; i < nodes_.size(); i++) {
      output.writeMessage(7, nodes_.get(i));
    }
    for (int i = 0; i < edges_.size(); i++) {
      output.writeMessage(8, edges_.get(i));
    }
    if (!getEntrypointNodeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, entrypointNodeName_);
    }
    for (int i = 0; i < variableDefs_.size(); i++) {
      output.writeMessage(10, variableDefs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (createdAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCreatedAt());
    }
    if (updatedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUpdatedAt());
    }
    if (!getWfSpecIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, wfSpecId_);
    }
    if (!getWfSpecNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, wfSpecName_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
    }
    for (int i = 0; i < nodes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, nodes_.get(i));
    }
    for (int i = 0; i < edges_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, edges_.get(i));
    }
    if (!getEntrypointNodeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, entrypointNodeName_);
    }
    for (int i = 0; i < variableDefs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, variableDefs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.proto.ThreadSpecPb)) {
      return super.equals(obj);
    }
    io.littlehorse.proto.ThreadSpecPb other = (io.littlehorse.proto.ThreadSpecPb) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
    if (hasUpdatedAt()) {
      if (!getUpdatedAt()
          .equals(other.getUpdatedAt())) return false;
    }
    if (!getWfSpecId()
        .equals(other.getWfSpecId())) return false;
    if (!getWfSpecName()
        .equals(other.getWfSpecName())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getNodesList()
        .equals(other.getNodesList())) return false;
    if (!getEdgesList()
        .equals(other.getEdgesList())) return false;
    if (!getEntrypointNodeName()
        .equals(other.getEntrypointNodeName())) return false;
    if (!getVariableDefsList()
        .equals(other.getVariableDefsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasUpdatedAt()) {
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
    }
    hash = (37 * hash) + WF_SPEC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWfSpecId().hashCode();
    hash = (37 * hash) + WF_SPEC_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getWfSpecName().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getNodesCount() > 0) {
      hash = (37 * hash) + NODES_FIELD_NUMBER;
      hash = (53 * hash) + getNodesList().hashCode();
    }
    if (getEdgesCount() > 0) {
      hash = (37 * hash) + EDGES_FIELD_NUMBER;
      hash = (53 * hash) + getEdgesList().hashCode();
    }
    hash = (37 * hash) + ENTRYPOINT_NODE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEntrypointNodeName().hashCode();
    if (getVariableDefsCount() > 0) {
      hash = (37 * hash) + VARIABLE_DEFS_FIELD_NUMBER;
      hash = (53 * hash) + getVariableDefsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.proto.ThreadSpecPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.ThreadSpecPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.proto.ThreadSpecPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lh_proto.ThreadSpecPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lh_proto.ThreadSpecPb)
      io.littlehorse.proto.ThreadSpecPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadSpecPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadSpecPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.proto.ThreadSpecPb.class, io.littlehorse.proto.ThreadSpecPb.Builder.class);
    }

    // Construct using io.littlehorse.proto.ThreadSpecPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNodesFieldBuilder();
        getEdgesFieldBuilder();
        getVariableDefsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (createdAtBuilder_ == null) {
        createdAt_ = null;
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }
      if (updatedAtBuilder_ == null) {
        updatedAt_ = null;
      } else {
        updatedAt_ = null;
        updatedAtBuilder_ = null;
      }
      wfSpecId_ = "";

      wfSpecName_ = "";

      name_ = "";

      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        nodesBuilder_.clear();
      }
      if (edgesBuilder_ == null) {
        edges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        edgesBuilder_.clear();
      }
      entrypointNodeName_ = "";

      if (variableDefsBuilder_ == null) {
        variableDefs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        variableDefsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_ThreadSpecPb_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.proto.ThreadSpecPb getDefaultInstanceForType() {
      return io.littlehorse.proto.ThreadSpecPb.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.proto.ThreadSpecPb build() {
      io.littlehorse.proto.ThreadSpecPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.proto.ThreadSpecPb buildPartial() {
      io.littlehorse.proto.ThreadSpecPb result = new io.littlehorse.proto.ThreadSpecPb(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (createdAtBuilder_ == null) {
        result.createdAt_ = createdAt_;
      } else {
        result.createdAt_ = createdAtBuilder_.build();
      }
      if (updatedAtBuilder_ == null) {
        result.updatedAt_ = updatedAt_;
      } else {
        result.updatedAt_ = updatedAtBuilder_.build();
      }
      result.wfSpecId_ = wfSpecId_;
      result.wfSpecName_ = wfSpecName_;
      result.name_ = name_;
      if (nodesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.nodes_ = nodes_;
      } else {
        result.nodes_ = nodesBuilder_.build();
      }
      if (edgesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          edges_ = java.util.Collections.unmodifiableList(edges_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.edges_ = edges_;
      } else {
        result.edges_ = edgesBuilder_.build();
      }
      result.entrypointNodeName_ = entrypointNodeName_;
      if (variableDefsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          variableDefs_ = java.util.Collections.unmodifiableList(variableDefs_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.variableDefs_ = variableDefs_;
      } else {
        result.variableDefs_ = variableDefsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.proto.ThreadSpecPb) {
        return mergeFrom((io.littlehorse.proto.ThreadSpecPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.proto.ThreadSpecPb other) {
      if (other == io.littlehorse.proto.ThreadSpecPb.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasUpdatedAt()) {
        mergeUpdatedAt(other.getUpdatedAt());
      }
      if (!other.getWfSpecId().isEmpty()) {
        wfSpecId_ = other.wfSpecId_;
        onChanged();
      }
      if (!other.getWfSpecName().isEmpty()) {
        wfSpecName_ = other.wfSpecName_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (nodesBuilder_ == null) {
        if (!other.nodes_.isEmpty()) {
          if (nodes_.isEmpty()) {
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNodesIsMutable();
            nodes_.addAll(other.nodes_);
          }
          onChanged();
        }
      } else {
        if (!other.nodes_.isEmpty()) {
          if (nodesBuilder_.isEmpty()) {
            nodesBuilder_.dispose();
            nodesBuilder_ = null;
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            nodesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNodesFieldBuilder() : null;
          } else {
            nodesBuilder_.addAllMessages(other.nodes_);
          }
        }
      }
      if (edgesBuilder_ == null) {
        if (!other.edges_.isEmpty()) {
          if (edges_.isEmpty()) {
            edges_ = other.edges_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEdgesIsMutable();
            edges_.addAll(other.edges_);
          }
          onChanged();
        }
      } else {
        if (!other.edges_.isEmpty()) {
          if (edgesBuilder_.isEmpty()) {
            edgesBuilder_.dispose();
            edgesBuilder_ = null;
            edges_ = other.edges_;
            bitField0_ = (bitField0_ & ~0x00000002);
            edgesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEdgesFieldBuilder() : null;
          } else {
            edgesBuilder_.addAllMessages(other.edges_);
          }
        }
      }
      if (!other.getEntrypointNodeName().isEmpty()) {
        entrypointNodeName_ = other.entrypointNodeName_;
        onChanged();
      }
      if (variableDefsBuilder_ == null) {
        if (!other.variableDefs_.isEmpty()) {
          if (variableDefs_.isEmpty()) {
            variableDefs_ = other.variableDefs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureVariableDefsIsMutable();
            variableDefs_.addAll(other.variableDefs_);
          }
          onChanged();
        }
      } else {
        if (!other.variableDefs_.isEmpty()) {
          if (variableDefsBuilder_.isEmpty()) {
            variableDefsBuilder_.dispose();
            variableDefsBuilder_ = null;
            variableDefs_ = other.variableDefs_;
            bitField0_ = (bitField0_ & ~0x00000004);
            variableDefsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVariableDefsFieldBuilder() : null;
          } else {
            variableDefsBuilder_.addAllMessages(other.variableDefs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.littlehorse.proto.ThreadSpecPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.littlehorse.proto.ThreadSpecPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return createdAtBuilder_ != null || createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
        onChanged();
      } else {
        createdAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
        onChanged();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (createdAt_ != null) {
          createdAt_ =
            com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
        } else {
          createdAt_ = value;
        }
        onChanged();
      } else {
        createdAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder clearCreatedAt() {
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
        onChanged();
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp updatedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return updatedAtBuilder_ != null || updatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedAt_ = value;
        onChanged();
      } else {
        updatedAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
        onChanged();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (updatedAt_ != null) {
          updatedAt_ =
            com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
        } else {
          updatedAt_ = value;
        }
        onChanged();
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public Builder clearUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = null;
        onChanged();
      } else {
        updatedAt_ = null;
        updatedAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      
      onChanged();
      return getUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }

    private java.lang.Object wfSpecId_ = "";
    /**
     * <code>string wf_spec_id = 4;</code>
     * @return The wfSpecId.
     */
    public java.lang.String getWfSpecId() {
      java.lang.Object ref = wfSpecId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wfSpecId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string wf_spec_id = 4;</code>
     * @return The bytes for wfSpecId.
     */
    public com.google.protobuf.ByteString
        getWfSpecIdBytes() {
      java.lang.Object ref = wfSpecId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wfSpecId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string wf_spec_id = 4;</code>
     * @param value The wfSpecId to set.
     * @return This builder for chaining.
     */
    public Builder setWfSpecId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wfSpecId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string wf_spec_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWfSpecId() {
      
      wfSpecId_ = getDefaultInstance().getWfSpecId();
      onChanged();
      return this;
    }
    /**
     * <code>string wf_spec_id = 4;</code>
     * @param value The bytes for wfSpecId to set.
     * @return This builder for chaining.
     */
    public Builder setWfSpecIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wfSpecId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object wfSpecName_ = "";
    /**
     * <code>string wf_spec_name = 5;</code>
     * @return The wfSpecName.
     */
    public java.lang.String getWfSpecName() {
      java.lang.Object ref = wfSpecName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wfSpecName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string wf_spec_name = 5;</code>
     * @return The bytes for wfSpecName.
     */
    public com.google.protobuf.ByteString
        getWfSpecNameBytes() {
      java.lang.Object ref = wfSpecName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wfSpecName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string wf_spec_name = 5;</code>
     * @param value The wfSpecName to set.
     * @return This builder for chaining.
     */
    public Builder setWfSpecName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wfSpecName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string wf_spec_name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWfSpecName() {
      
      wfSpecName_ = getDefaultInstance().getWfSpecName();
      onChanged();
      return this;
    }
    /**
     * <code>string wf_spec_name = 5;</code>
     * @param value The bytes for wfSpecName to set.
     * @return This builder for chaining.
     */
    public Builder setWfSpecNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wfSpecName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 6;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 6;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 6;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 6;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.littlehorse.proto.NodePb> nodes_ =
      java.util.Collections.emptyList();
    private void ensureNodesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        nodes_ = new java.util.ArrayList<io.littlehorse.proto.NodePb>(nodes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.proto.NodePb, io.littlehorse.proto.NodePb.Builder, io.littlehorse.proto.NodePbOrBuilder> nodesBuilder_;

    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public java.util.List<io.littlehorse.proto.NodePb> getNodesList() {
      if (nodesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nodes_);
      } else {
        return nodesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public int getNodesCount() {
      if (nodesBuilder_ == null) {
        return nodes_.size();
      } else {
        return nodesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public io.littlehorse.proto.NodePb getNodes(int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);
      } else {
        return nodesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public Builder setNodes(
        int index, io.littlehorse.proto.NodePb value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.set(index, value);
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public Builder setNodes(
        int index, io.littlehorse.proto.NodePb.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public Builder addNodes(io.littlehorse.proto.NodePb value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public Builder addNodes(
        int index, io.littlehorse.proto.NodePb value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(index, value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public Builder addNodes(
        io.littlehorse.proto.NodePb.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public Builder addNodes(
        int index, io.littlehorse.proto.NodePb.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public Builder addAllNodes(
        java.lang.Iterable<? extends io.littlehorse.proto.NodePb> values) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodes_);
        onChanged();
      } else {
        nodesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public Builder clearNodes() {
      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        nodesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public Builder removeNodes(int index) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.remove(index);
        onChanged();
      } else {
        nodesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public io.littlehorse.proto.NodePb.Builder getNodesBuilder(
        int index) {
      return getNodesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public io.littlehorse.proto.NodePbOrBuilder getNodesOrBuilder(
        int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);  } else {
        return nodesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public java.util.List<? extends io.littlehorse.proto.NodePbOrBuilder> 
         getNodesOrBuilderList() {
      if (nodesBuilder_ != null) {
        return nodesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nodes_);
      }
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public io.littlehorse.proto.NodePb.Builder addNodesBuilder() {
      return getNodesFieldBuilder().addBuilder(
          io.littlehorse.proto.NodePb.getDefaultInstance());
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public io.littlehorse.proto.NodePb.Builder addNodesBuilder(
        int index) {
      return getNodesFieldBuilder().addBuilder(
          index, io.littlehorse.proto.NodePb.getDefaultInstance());
    }
    /**
     * <code>repeated .lh_proto.NodePb nodes = 7;</code>
     */
    public java.util.List<io.littlehorse.proto.NodePb.Builder> 
         getNodesBuilderList() {
      return getNodesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.proto.NodePb, io.littlehorse.proto.NodePb.Builder, io.littlehorse.proto.NodePbOrBuilder> 
        getNodesFieldBuilder() {
      if (nodesBuilder_ == null) {
        nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.littlehorse.proto.NodePb, io.littlehorse.proto.NodePb.Builder, io.littlehorse.proto.NodePbOrBuilder>(
                nodes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        nodes_ = null;
      }
      return nodesBuilder_;
    }

    private java.util.List<io.littlehorse.proto.EdgePb> edges_ =
      java.util.Collections.emptyList();
    private void ensureEdgesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        edges_ = new java.util.ArrayList<io.littlehorse.proto.EdgePb>(edges_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.proto.EdgePb, io.littlehorse.proto.EdgePb.Builder, io.littlehorse.proto.EdgePbOrBuilder> edgesBuilder_;

    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public java.util.List<io.littlehorse.proto.EdgePb> getEdgesList() {
      if (edgesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(edges_);
      } else {
        return edgesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public int getEdgesCount() {
      if (edgesBuilder_ == null) {
        return edges_.size();
      } else {
        return edgesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public io.littlehorse.proto.EdgePb getEdges(int index) {
      if (edgesBuilder_ == null) {
        return edges_.get(index);
      } else {
        return edgesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public Builder setEdges(
        int index, io.littlehorse.proto.EdgePb value) {
      if (edgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEdgesIsMutable();
        edges_.set(index, value);
        onChanged();
      } else {
        edgesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public Builder setEdges(
        int index, io.littlehorse.proto.EdgePb.Builder builderForValue) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        edges_.set(index, builderForValue.build());
        onChanged();
      } else {
        edgesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public Builder addEdges(io.littlehorse.proto.EdgePb value) {
      if (edgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEdgesIsMutable();
        edges_.add(value);
        onChanged();
      } else {
        edgesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public Builder addEdges(
        int index, io.littlehorse.proto.EdgePb value) {
      if (edgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEdgesIsMutable();
        edges_.add(index, value);
        onChanged();
      } else {
        edgesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public Builder addEdges(
        io.littlehorse.proto.EdgePb.Builder builderForValue) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        edges_.add(builderForValue.build());
        onChanged();
      } else {
        edgesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public Builder addEdges(
        int index, io.littlehorse.proto.EdgePb.Builder builderForValue) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        edges_.add(index, builderForValue.build());
        onChanged();
      } else {
        edgesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public Builder addAllEdges(
        java.lang.Iterable<? extends io.littlehorse.proto.EdgePb> values) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, edges_);
        onChanged();
      } else {
        edgesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public Builder clearEdges() {
      if (edgesBuilder_ == null) {
        edges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        edgesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public Builder removeEdges(int index) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        edges_.remove(index);
        onChanged();
      } else {
        edgesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public io.littlehorse.proto.EdgePb.Builder getEdgesBuilder(
        int index) {
      return getEdgesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public io.littlehorse.proto.EdgePbOrBuilder getEdgesOrBuilder(
        int index) {
      if (edgesBuilder_ == null) {
        return edges_.get(index);  } else {
        return edgesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public java.util.List<? extends io.littlehorse.proto.EdgePbOrBuilder> 
         getEdgesOrBuilderList() {
      if (edgesBuilder_ != null) {
        return edgesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(edges_);
      }
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public io.littlehorse.proto.EdgePb.Builder addEdgesBuilder() {
      return getEdgesFieldBuilder().addBuilder(
          io.littlehorse.proto.EdgePb.getDefaultInstance());
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public io.littlehorse.proto.EdgePb.Builder addEdgesBuilder(
        int index) {
      return getEdgesFieldBuilder().addBuilder(
          index, io.littlehorse.proto.EdgePb.getDefaultInstance());
    }
    /**
     * <code>repeated .lh_proto.EdgePb edges = 8;</code>
     */
    public java.util.List<io.littlehorse.proto.EdgePb.Builder> 
         getEdgesBuilderList() {
      return getEdgesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.proto.EdgePb, io.littlehorse.proto.EdgePb.Builder, io.littlehorse.proto.EdgePbOrBuilder> 
        getEdgesFieldBuilder() {
      if (edgesBuilder_ == null) {
        edgesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.littlehorse.proto.EdgePb, io.littlehorse.proto.EdgePb.Builder, io.littlehorse.proto.EdgePbOrBuilder>(
                edges_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        edges_ = null;
      }
      return edgesBuilder_;
    }

    private java.lang.Object entrypointNodeName_ = "";
    /**
     * <code>string entrypoint_node_name = 9;</code>
     * @return The entrypointNodeName.
     */
    public java.lang.String getEntrypointNodeName() {
      java.lang.Object ref = entrypointNodeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entrypointNodeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string entrypoint_node_name = 9;</code>
     * @return The bytes for entrypointNodeName.
     */
    public com.google.protobuf.ByteString
        getEntrypointNodeNameBytes() {
      java.lang.Object ref = entrypointNodeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entrypointNodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entrypoint_node_name = 9;</code>
     * @param value The entrypointNodeName to set.
     * @return This builder for chaining.
     */
    public Builder setEntrypointNodeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      entrypointNodeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string entrypoint_node_name = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntrypointNodeName() {
      
      entrypointNodeName_ = getDefaultInstance().getEntrypointNodeName();
      onChanged();
      return this;
    }
    /**
     * <code>string entrypoint_node_name = 9;</code>
     * @param value The bytes for entrypointNodeName to set.
     * @return This builder for chaining.
     */
    public Builder setEntrypointNodeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      entrypointNodeName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.littlehorse.proto.VariableDefPb> variableDefs_ =
      java.util.Collections.emptyList();
    private void ensureVariableDefsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        variableDefs_ = new java.util.ArrayList<io.littlehorse.proto.VariableDefPb>(variableDefs_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.proto.VariableDefPb, io.littlehorse.proto.VariableDefPb.Builder, io.littlehorse.proto.VariableDefPbOrBuilder> variableDefsBuilder_;

    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public java.util.List<io.littlehorse.proto.VariableDefPb> getVariableDefsList() {
      if (variableDefsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(variableDefs_);
      } else {
        return variableDefsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public int getVariableDefsCount() {
      if (variableDefsBuilder_ == null) {
        return variableDefs_.size();
      } else {
        return variableDefsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public io.littlehorse.proto.VariableDefPb getVariableDefs(int index) {
      if (variableDefsBuilder_ == null) {
        return variableDefs_.get(index);
      } else {
        return variableDefsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public Builder setVariableDefs(
        int index, io.littlehorse.proto.VariableDefPb value) {
      if (variableDefsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariableDefsIsMutable();
        variableDefs_.set(index, value);
        onChanged();
      } else {
        variableDefsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public Builder setVariableDefs(
        int index, io.littlehorse.proto.VariableDefPb.Builder builderForValue) {
      if (variableDefsBuilder_ == null) {
        ensureVariableDefsIsMutable();
        variableDefs_.set(index, builderForValue.build());
        onChanged();
      } else {
        variableDefsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public Builder addVariableDefs(io.littlehorse.proto.VariableDefPb value) {
      if (variableDefsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariableDefsIsMutable();
        variableDefs_.add(value);
        onChanged();
      } else {
        variableDefsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public Builder addVariableDefs(
        int index, io.littlehorse.proto.VariableDefPb value) {
      if (variableDefsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariableDefsIsMutable();
        variableDefs_.add(index, value);
        onChanged();
      } else {
        variableDefsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public Builder addVariableDefs(
        io.littlehorse.proto.VariableDefPb.Builder builderForValue) {
      if (variableDefsBuilder_ == null) {
        ensureVariableDefsIsMutable();
        variableDefs_.add(builderForValue.build());
        onChanged();
      } else {
        variableDefsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public Builder addVariableDefs(
        int index, io.littlehorse.proto.VariableDefPb.Builder builderForValue) {
      if (variableDefsBuilder_ == null) {
        ensureVariableDefsIsMutable();
        variableDefs_.add(index, builderForValue.build());
        onChanged();
      } else {
        variableDefsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public Builder addAllVariableDefs(
        java.lang.Iterable<? extends io.littlehorse.proto.VariableDefPb> values) {
      if (variableDefsBuilder_ == null) {
        ensureVariableDefsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, variableDefs_);
        onChanged();
      } else {
        variableDefsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public Builder clearVariableDefs() {
      if (variableDefsBuilder_ == null) {
        variableDefs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        variableDefsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public Builder removeVariableDefs(int index) {
      if (variableDefsBuilder_ == null) {
        ensureVariableDefsIsMutable();
        variableDefs_.remove(index);
        onChanged();
      } else {
        variableDefsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public io.littlehorse.proto.VariableDefPb.Builder getVariableDefsBuilder(
        int index) {
      return getVariableDefsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public io.littlehorse.proto.VariableDefPbOrBuilder getVariableDefsOrBuilder(
        int index) {
      if (variableDefsBuilder_ == null) {
        return variableDefs_.get(index);  } else {
        return variableDefsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public java.util.List<? extends io.littlehorse.proto.VariableDefPbOrBuilder> 
         getVariableDefsOrBuilderList() {
      if (variableDefsBuilder_ != null) {
        return variableDefsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(variableDefs_);
      }
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public io.littlehorse.proto.VariableDefPb.Builder addVariableDefsBuilder() {
      return getVariableDefsFieldBuilder().addBuilder(
          io.littlehorse.proto.VariableDefPb.getDefaultInstance());
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public io.littlehorse.proto.VariableDefPb.Builder addVariableDefsBuilder(
        int index) {
      return getVariableDefsFieldBuilder().addBuilder(
          index, io.littlehorse.proto.VariableDefPb.getDefaultInstance());
    }
    /**
     * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
     */
    public java.util.List<io.littlehorse.proto.VariableDefPb.Builder> 
         getVariableDefsBuilderList() {
      return getVariableDefsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.proto.VariableDefPb, io.littlehorse.proto.VariableDefPb.Builder, io.littlehorse.proto.VariableDefPbOrBuilder> 
        getVariableDefsFieldBuilder() {
      if (variableDefsBuilder_ == null) {
        variableDefsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.littlehorse.proto.VariableDefPb, io.littlehorse.proto.VariableDefPb.Builder, io.littlehorse.proto.VariableDefPbOrBuilder>(
                variableDefs_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        variableDefs_ = null;
      }
      return variableDefsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lh_proto.ThreadSpecPb)
  }

  // @@protoc_insertion_point(class_scope:lh_proto.ThreadSpecPb)
  private static final io.littlehorse.proto.ThreadSpecPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.proto.ThreadSpecPb();
  }

  public static io.littlehorse.proto.ThreadSpecPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ThreadSpecPb>
      PARSER = new com.google.protobuf.AbstractParser<ThreadSpecPb>() {
    @java.lang.Override
    public ThreadSpecPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ThreadSpecPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ThreadSpecPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ThreadSpecPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.proto.ThreadSpecPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

