// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

public interface ThreadSpecPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lh_proto.ThreadSpecPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>string wf_spec_id = 4;</code>
   * @return The wfSpecId.
   */
  java.lang.String getWfSpecId();
  /**
   * <code>string wf_spec_id = 4;</code>
   * @return The bytes for wfSpecId.
   */
  com.google.protobuf.ByteString
      getWfSpecIdBytes();

  /**
   * <code>string wf_spec_name = 5;</code>
   * @return The wfSpecName.
   */
  java.lang.String getWfSpecName();
  /**
   * <code>string wf_spec_name = 5;</code>
   * @return The bytes for wfSpecName.
   */
  com.google.protobuf.ByteString
      getWfSpecNameBytes();

  /**
   * <code>string name = 6;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  java.util.List<io.littlehorse.proto.NodePb> 
      getNodesList();
  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  io.littlehorse.proto.NodePb getNodes(int index);
  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  java.util.List<? extends io.littlehorse.proto.NodePbOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .lh_proto.NodePb nodes = 7;</code>
   */
  io.littlehorse.proto.NodePbOrBuilder getNodesOrBuilder(
      int index);

  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  java.util.List<io.littlehorse.proto.EdgePb> 
      getEdgesList();
  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  io.littlehorse.proto.EdgePb getEdges(int index);
  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  int getEdgesCount();
  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  java.util.List<? extends io.littlehorse.proto.EdgePbOrBuilder> 
      getEdgesOrBuilderList();
  /**
   * <code>repeated .lh_proto.EdgePb edges = 8;</code>
   */
  io.littlehorse.proto.EdgePbOrBuilder getEdgesOrBuilder(
      int index);

  /**
   * <code>string entrypoint_node_name = 9;</code>
   * @return The entrypointNodeName.
   */
  java.lang.String getEntrypointNodeName();
  /**
   * <code>string entrypoint_node_name = 9;</code>
   * @return The bytes for entrypointNodeName.
   */
  com.google.protobuf.ByteString
      getEntrypointNodeNameBytes();

  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  java.util.List<io.littlehorse.proto.VariableDefPb> 
      getVariableDefsList();
  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  io.littlehorse.proto.VariableDefPb getVariableDefs(int index);
  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  int getVariableDefsCount();
  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  java.util.List<? extends io.littlehorse.proto.VariableDefPbOrBuilder> 
      getVariableDefsOrBuilderList();
  /**
   * <code>repeated .lh_proto.VariableDefPb variable_defs = 10;</code>
   */
  io.littlehorse.proto.VariableDefPbOrBuilder getVariableDefsOrBuilder(
      int index);
}
