// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

public interface ThreadRunPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lh_proto.ThreadRunPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
   */
  int getVariablesCount();
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
   */
  boolean containsVariables(
      java.lang.String key);
  /**
   * Use {@link #getVariablesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb>
  getVariables();
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
   */
  java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb>
  getVariablesMap();
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
   */

  io.littlehorse.proto.VariableValuePb getVariablesOrDefault(
      java.lang.String key,
      io.littlehorse.proto.VariableValuePb defaultValue);
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variables = 1;</code>
   */

  io.littlehorse.proto.VariableValuePb getVariablesOrThrow(
      java.lang.String key);

  /**
   * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
   * @return Whether the currentTaskRun field is set.
   */
  boolean hasCurrentTaskRun();
  /**
   * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
   * @return The currentTaskRun.
   */
  io.littlehorse.proto.TaskRunPb getCurrentTaskRun();
  /**
   * <code>.lh_proto.TaskRunPb current_task_run = 2;</code>
   */
  io.littlehorse.proto.TaskRunPbOrBuilder getCurrentTaskRunOrBuilder();

  /**
   * <code>.lh_proto.LHStatusPb status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.lh_proto.LHStatusPb status = 3;</code>
   * @return The status.
   */
  io.littlehorse.proto.LHStatusPb getStatus();

  /**
   * <code>string current_node = 4;</code>
   * @return Whether the currentNode field is set.
   */
  boolean hasCurrentNode();
  /**
   * <code>string current_node = 4;</code>
   * @return The currentNode.
   */
  java.lang.String getCurrentNode();
  /**
   * <code>string current_node = 4;</code>
   * @return The bytes for currentNode.
   */
  com.google.protobuf.ByteString
      getCurrentNodeBytes();
}
