// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

public interface VariableDefPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lh_proto.VariableDefPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>.lh_proto.VariableTypePb type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.lh_proto.VariableTypePb type = 4;</code>
   * @return The type.
   */
  io.littlehorse.proto.VariableTypePb getType();

  /**
   * <code>string thread_spec_id = 5;</code>
   * @return The threadSpecId.
   */
  java.lang.String getThreadSpecId();
  /**
   * <code>string thread_spec_id = 5;</code>
   * @return The bytes for threadSpecId.
   */
  com.google.protobuf.ByteString
      getThreadSpecIdBytes();

  /**
   * <code>string variable_name = 6;</code>
   * @return The variableName.
   */
  java.lang.String getVariableName();
  /**
   * <code>string variable_name = 6;</code>
   * @return The bytes for variableName.
   */
  com.google.protobuf.ByteString
      getVariableNameBytes();
}
