// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

public interface VariableValuePbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lh_proto.VariableValuePb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.lh_proto.VariableTypePb type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.lh_proto.VariableTypePb type = 1;</code>
   * @return The type.
   */
  io.littlehorse.proto.VariableTypePb getType();

  /**
   * <code>bytes serialized_value = 2;</code>
   * @return The serializedValue.
   */
  com.google.protobuf.ByteString getSerializedValue();
}
