// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

public interface WFRunRequestPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lh_proto.WFRunRequestPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wf_run_id = 1;</code>
   * @return The wfRunId.
   */
  java.lang.String getWfRunId();
  /**
   * <code>string wf_run_id = 1;</code>
   * @return The bytes for wfRunId.
   */
  com.google.protobuf.ByteString
      getWfRunIdBytes();

  /**
   * <code>string wf_spec_id = 2;</code>
   * @return The wfSpecId.
   */
  java.lang.String getWfSpecId();
  /**
   * <code>string wf_spec_id = 2;</code>
   * @return The bytes for wfSpecId.
   */
  com.google.protobuf.ByteString
      getWfSpecIdBytes();

  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
   */
  int getVariableValuesCount();
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
   */
  boolean containsVariableValues(
      java.lang.String key);
  /**
   * Use {@link #getVariableValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb>
  getVariableValues();
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
   */
  java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb>
  getVariableValuesMap();
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
   */

  io.littlehorse.proto.VariableValuePb getVariableValuesOrDefault(
      java.lang.String key,
      io.littlehorse.proto.VariableValuePb defaultValue);
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
   */

  io.littlehorse.proto.VariableValuePb getVariableValuesOrThrow(
      java.lang.String key);
}
