// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

public interface WFRunEventPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lh_proto.WFRunEventPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wf_run_id = 1;</code>
   * @return The wfRunId.
   */
  java.lang.String getWfRunId();
  /**
   * <code>string wf_run_id = 1;</code>
   * @return The bytes for wfRunId.
   */
  com.google.protobuf.ByteString
      getWfRunIdBytes();

  /**
   * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
   * @return Whether the runRequest field is set.
   */
  boolean hasRunRequest();
  /**
   * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
   * @return The runRequest.
   */
  io.littlehorse.proto.WFRunRequestPb getRunRequest();
  /**
   * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
   */
  io.littlehorse.proto.WFRunRequestPbOrBuilder getRunRequestOrBuilder();

  /**
   * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
   * @return Whether the startedEvent field is set.
   */
  boolean hasStartedEvent();
  /**
   * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
   * @return The startedEvent.
   */
  io.littlehorse.proto.TaskStartedEventPb getStartedEvent();
  /**
   * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
   */
  io.littlehorse.proto.TaskStartedEventPbOrBuilder getStartedEventOrBuilder();

  /**
   * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
   * @return Whether the completedEvent field is set.
   */
  boolean hasCompletedEvent();
  /**
   * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
   * @return The completedEvent.
   */
  io.littlehorse.proto.TaskCompletedEventPb getCompletedEvent();
  /**
   * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
   */
  io.littlehorse.proto.TaskCompletedEventPbOrBuilder getCompletedEventOrBuilder();
}
