// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

/**
 * Protobuf type {@code lh_proto.WFRunEventPb}
 */
public final class WFRunEventPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lh_proto.WFRunEventPb)
    WFRunEventPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WFRunEventPb.newBuilder() to construct.
  private WFRunEventPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WFRunEventPb() {
    wfRunId_ = "";
    wfSpecId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WFRunEventPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WFRunEventPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            wfRunId_ = s;
            break;
          }
          case 18: {
            io.littlehorse.proto.WFRunRequestPb.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = runRequest_.toBuilder();
            }
            runRequest_ = input.readMessage(io.littlehorse.proto.WFRunRequestPb.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(runRequest_);
              runRequest_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 26: {
            io.littlehorse.proto.TaskStartedEventPb.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = startedEvent_.toBuilder();
            }
            startedEvent_ = input.readMessage(io.littlehorse.proto.TaskStartedEventPb.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startedEvent_);
              startedEvent_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 34: {
            io.littlehorse.proto.TaskCompletedEventPb.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = completedEvent_.toBuilder();
            }
            completedEvent_ = input.readMessage(io.littlehorse.proto.TaskCompletedEventPb.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(completedEvent_);
              completedEvent_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            wfSpecId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunEventPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunEventPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.proto.WFRunEventPb.class, io.littlehorse.proto.WFRunEventPb.Builder.class);
  }

  private int bitField0_;
  public static final int WF_RUN_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object wfRunId_;
  /**
   * <code>string wf_run_id = 1;</code>
   * @return The wfRunId.
   */
  @java.lang.Override
  public java.lang.String getWfRunId() {
    java.lang.Object ref = wfRunId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wfRunId_ = s;
      return s;
    }
  }
  /**
   * <code>string wf_run_id = 1;</code>
   * @return The bytes for wfRunId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWfRunIdBytes() {
    java.lang.Object ref = wfRunId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wfRunId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUN_REQUEST_FIELD_NUMBER = 2;
  private io.littlehorse.proto.WFRunRequestPb runRequest_;
  /**
   * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
   * @return Whether the runRequest field is set.
   */
  @java.lang.Override
  public boolean hasRunRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
   * @return The runRequest.
   */
  @java.lang.Override
  public io.littlehorse.proto.WFRunRequestPb getRunRequest() {
    return runRequest_ == null ? io.littlehorse.proto.WFRunRequestPb.getDefaultInstance() : runRequest_;
  }
  /**
   * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.WFRunRequestPbOrBuilder getRunRequestOrBuilder() {
    return runRequest_ == null ? io.littlehorse.proto.WFRunRequestPb.getDefaultInstance() : runRequest_;
  }

  public static final int STARTED_EVENT_FIELD_NUMBER = 3;
  private io.littlehorse.proto.TaskStartedEventPb startedEvent_;
  /**
   * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
   * @return Whether the startedEvent field is set.
   */
  @java.lang.Override
  public boolean hasStartedEvent() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
   * @return The startedEvent.
   */
  @java.lang.Override
  public io.littlehorse.proto.TaskStartedEventPb getStartedEvent() {
    return startedEvent_ == null ? io.littlehorse.proto.TaskStartedEventPb.getDefaultInstance() : startedEvent_;
  }
  /**
   * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.TaskStartedEventPbOrBuilder getStartedEventOrBuilder() {
    return startedEvent_ == null ? io.littlehorse.proto.TaskStartedEventPb.getDefaultInstance() : startedEvent_;
  }

  public static final int COMPLETED_EVENT_FIELD_NUMBER = 4;
  private io.littlehorse.proto.TaskCompletedEventPb completedEvent_;
  /**
   * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
   * @return Whether the completedEvent field is set.
   */
  @java.lang.Override
  public boolean hasCompletedEvent() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
   * @return The completedEvent.
   */
  @java.lang.Override
  public io.littlehorse.proto.TaskCompletedEventPb getCompletedEvent() {
    return completedEvent_ == null ? io.littlehorse.proto.TaskCompletedEventPb.getDefaultInstance() : completedEvent_;
  }
  /**
   * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.TaskCompletedEventPbOrBuilder getCompletedEventOrBuilder() {
    return completedEvent_ == null ? io.littlehorse.proto.TaskCompletedEventPb.getDefaultInstance() : completedEvent_;
  }

  public static final int WF_SPEC_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object wfSpecId_;
  /**
   * <code>string wf_spec_id = 5;</code>
   * @return The wfSpecId.
   */
  @java.lang.Override
  public java.lang.String getWfSpecId() {
    java.lang.Object ref = wfSpecId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wfSpecId_ = s;
      return s;
    }
  }
  /**
   * <code>string wf_spec_id = 5;</code>
   * @return The bytes for wfSpecId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWfSpecIdBytes() {
    java.lang.Object ref = wfSpecId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wfSpecId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWfRunIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, wfRunId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getRunRequest());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getStartedEvent());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getCompletedEvent());
    }
    if (!getWfSpecIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, wfSpecId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWfRunIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, wfRunId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRunRequest());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStartedEvent());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCompletedEvent());
    }
    if (!getWfSpecIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, wfSpecId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.proto.WFRunEventPb)) {
      return super.equals(obj);
    }
    io.littlehorse.proto.WFRunEventPb other = (io.littlehorse.proto.WFRunEventPb) obj;

    if (!getWfRunId()
        .equals(other.getWfRunId())) return false;
    if (hasRunRequest() != other.hasRunRequest()) return false;
    if (hasRunRequest()) {
      if (!getRunRequest()
          .equals(other.getRunRequest())) return false;
    }
    if (hasStartedEvent() != other.hasStartedEvent()) return false;
    if (hasStartedEvent()) {
      if (!getStartedEvent()
          .equals(other.getStartedEvent())) return false;
    }
    if (hasCompletedEvent() != other.hasCompletedEvent()) return false;
    if (hasCompletedEvent()) {
      if (!getCompletedEvent()
          .equals(other.getCompletedEvent())) return false;
    }
    if (!getWfSpecId()
        .equals(other.getWfSpecId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WF_RUN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWfRunId().hashCode();
    if (hasRunRequest()) {
      hash = (37 * hash) + RUN_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getRunRequest().hashCode();
    }
    if (hasStartedEvent()) {
      hash = (37 * hash) + STARTED_EVENT_FIELD_NUMBER;
      hash = (53 * hash) + getStartedEvent().hashCode();
    }
    if (hasCompletedEvent()) {
      hash = (37 * hash) + COMPLETED_EVENT_FIELD_NUMBER;
      hash = (53 * hash) + getCompletedEvent().hashCode();
    }
    hash = (37 * hash) + WF_SPEC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWfSpecId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.proto.WFRunEventPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.WFRunEventPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunEventPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.WFRunEventPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunEventPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.WFRunEventPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunEventPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.WFRunEventPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunEventPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.WFRunEventPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunEventPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.WFRunEventPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.proto.WFRunEventPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lh_proto.WFRunEventPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lh_proto.WFRunEventPb)
      io.littlehorse.proto.WFRunEventPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunEventPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunEventPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.proto.WFRunEventPb.class, io.littlehorse.proto.WFRunEventPb.Builder.class);
    }

    // Construct using io.littlehorse.proto.WFRunEventPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRunRequestFieldBuilder();
        getStartedEventFieldBuilder();
        getCompletedEventFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      wfRunId_ = "";

      if (runRequestBuilder_ == null) {
        runRequest_ = null;
      } else {
        runRequestBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (startedEventBuilder_ == null) {
        startedEvent_ = null;
      } else {
        startedEventBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (completedEventBuilder_ == null) {
        completedEvent_ = null;
      } else {
        completedEventBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      wfSpecId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunEventPb_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.proto.WFRunEventPb getDefaultInstanceForType() {
      return io.littlehorse.proto.WFRunEventPb.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.proto.WFRunEventPb build() {
      io.littlehorse.proto.WFRunEventPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.proto.WFRunEventPb buildPartial() {
      io.littlehorse.proto.WFRunEventPb result = new io.littlehorse.proto.WFRunEventPb(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.wfRunId_ = wfRunId_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (runRequestBuilder_ == null) {
          result.runRequest_ = runRequest_;
        } else {
          result.runRequest_ = runRequestBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (startedEventBuilder_ == null) {
          result.startedEvent_ = startedEvent_;
        } else {
          result.startedEvent_ = startedEventBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (completedEventBuilder_ == null) {
          result.completedEvent_ = completedEvent_;
        } else {
          result.completedEvent_ = completedEventBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      result.wfSpecId_ = wfSpecId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.proto.WFRunEventPb) {
        return mergeFrom((io.littlehorse.proto.WFRunEventPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.proto.WFRunEventPb other) {
      if (other == io.littlehorse.proto.WFRunEventPb.getDefaultInstance()) return this;
      if (!other.getWfRunId().isEmpty()) {
        wfRunId_ = other.wfRunId_;
        onChanged();
      }
      if (other.hasRunRequest()) {
        mergeRunRequest(other.getRunRequest());
      }
      if (other.hasStartedEvent()) {
        mergeStartedEvent(other.getStartedEvent());
      }
      if (other.hasCompletedEvent()) {
        mergeCompletedEvent(other.getCompletedEvent());
      }
      if (!other.getWfSpecId().isEmpty()) {
        wfSpecId_ = other.wfSpecId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.littlehorse.proto.WFRunEventPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.littlehorse.proto.WFRunEventPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object wfRunId_ = "";
    /**
     * <code>string wf_run_id = 1;</code>
     * @return The wfRunId.
     */
    public java.lang.String getWfRunId() {
      java.lang.Object ref = wfRunId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wfRunId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string wf_run_id = 1;</code>
     * @return The bytes for wfRunId.
     */
    public com.google.protobuf.ByteString
        getWfRunIdBytes() {
      java.lang.Object ref = wfRunId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wfRunId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string wf_run_id = 1;</code>
     * @param value The wfRunId to set.
     * @return This builder for chaining.
     */
    public Builder setWfRunId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wfRunId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string wf_run_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWfRunId() {
      
      wfRunId_ = getDefaultInstance().getWfRunId();
      onChanged();
      return this;
    }
    /**
     * <code>string wf_run_id = 1;</code>
     * @param value The bytes for wfRunId to set.
     * @return This builder for chaining.
     */
    public Builder setWfRunIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wfRunId_ = value;
      onChanged();
      return this;
    }

    private io.littlehorse.proto.WFRunRequestPb runRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.proto.WFRunRequestPb, io.littlehorse.proto.WFRunRequestPb.Builder, io.littlehorse.proto.WFRunRequestPbOrBuilder> runRequestBuilder_;
    /**
     * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
     * @return Whether the runRequest field is set.
     */
    public boolean hasRunRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
     * @return The runRequest.
     */
    public io.littlehorse.proto.WFRunRequestPb getRunRequest() {
      if (runRequestBuilder_ == null) {
        return runRequest_ == null ? io.littlehorse.proto.WFRunRequestPb.getDefaultInstance() : runRequest_;
      } else {
        return runRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
     */
    public Builder setRunRequest(io.littlehorse.proto.WFRunRequestPb value) {
      if (runRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        runRequest_ = value;
        onChanged();
      } else {
        runRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
     */
    public Builder setRunRequest(
        io.littlehorse.proto.WFRunRequestPb.Builder builderForValue) {
      if (runRequestBuilder_ == null) {
        runRequest_ = builderForValue.build();
        onChanged();
      } else {
        runRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
     */
    public Builder mergeRunRequest(io.littlehorse.proto.WFRunRequestPb value) {
      if (runRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            runRequest_ != null &&
            runRequest_ != io.littlehorse.proto.WFRunRequestPb.getDefaultInstance()) {
          runRequest_ =
            io.littlehorse.proto.WFRunRequestPb.newBuilder(runRequest_).mergeFrom(value).buildPartial();
        } else {
          runRequest_ = value;
        }
        onChanged();
      } else {
        runRequestBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
     */
    public Builder clearRunRequest() {
      if (runRequestBuilder_ == null) {
        runRequest_ = null;
        onChanged();
      } else {
        runRequestBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
     */
    public io.littlehorse.proto.WFRunRequestPb.Builder getRunRequestBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRunRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
     */
    public io.littlehorse.proto.WFRunRequestPbOrBuilder getRunRequestOrBuilder() {
      if (runRequestBuilder_ != null) {
        return runRequestBuilder_.getMessageOrBuilder();
      } else {
        return runRequest_ == null ?
            io.littlehorse.proto.WFRunRequestPb.getDefaultInstance() : runRequest_;
      }
    }
    /**
     * <code>.lh_proto.WFRunRequestPb run_request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.proto.WFRunRequestPb, io.littlehorse.proto.WFRunRequestPb.Builder, io.littlehorse.proto.WFRunRequestPbOrBuilder> 
        getRunRequestFieldBuilder() {
      if (runRequestBuilder_ == null) {
        runRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.proto.WFRunRequestPb, io.littlehorse.proto.WFRunRequestPb.Builder, io.littlehorse.proto.WFRunRequestPbOrBuilder>(
                getRunRequest(),
                getParentForChildren(),
                isClean());
        runRequest_ = null;
      }
      return runRequestBuilder_;
    }

    private io.littlehorse.proto.TaskStartedEventPb startedEvent_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.proto.TaskStartedEventPb, io.littlehorse.proto.TaskStartedEventPb.Builder, io.littlehorse.proto.TaskStartedEventPbOrBuilder> startedEventBuilder_;
    /**
     * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
     * @return Whether the startedEvent field is set.
     */
    public boolean hasStartedEvent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
     * @return The startedEvent.
     */
    public io.littlehorse.proto.TaskStartedEventPb getStartedEvent() {
      if (startedEventBuilder_ == null) {
        return startedEvent_ == null ? io.littlehorse.proto.TaskStartedEventPb.getDefaultInstance() : startedEvent_;
      } else {
        return startedEventBuilder_.getMessage();
      }
    }
    /**
     * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
     */
    public Builder setStartedEvent(io.littlehorse.proto.TaskStartedEventPb value) {
      if (startedEventBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startedEvent_ = value;
        onChanged();
      } else {
        startedEventBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
     */
    public Builder setStartedEvent(
        io.littlehorse.proto.TaskStartedEventPb.Builder builderForValue) {
      if (startedEventBuilder_ == null) {
        startedEvent_ = builderForValue.build();
        onChanged();
      } else {
        startedEventBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
     */
    public Builder mergeStartedEvent(io.littlehorse.proto.TaskStartedEventPb value) {
      if (startedEventBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            startedEvent_ != null &&
            startedEvent_ != io.littlehorse.proto.TaskStartedEventPb.getDefaultInstance()) {
          startedEvent_ =
            io.littlehorse.proto.TaskStartedEventPb.newBuilder(startedEvent_).mergeFrom(value).buildPartial();
        } else {
          startedEvent_ = value;
        }
        onChanged();
      } else {
        startedEventBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
     */
    public Builder clearStartedEvent() {
      if (startedEventBuilder_ == null) {
        startedEvent_ = null;
        onChanged();
      } else {
        startedEventBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
     */
    public io.littlehorse.proto.TaskStartedEventPb.Builder getStartedEventBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getStartedEventFieldBuilder().getBuilder();
    }
    /**
     * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
     */
    public io.littlehorse.proto.TaskStartedEventPbOrBuilder getStartedEventOrBuilder() {
      if (startedEventBuilder_ != null) {
        return startedEventBuilder_.getMessageOrBuilder();
      } else {
        return startedEvent_ == null ?
            io.littlehorse.proto.TaskStartedEventPb.getDefaultInstance() : startedEvent_;
      }
    }
    /**
     * <code>.lh_proto.TaskStartedEventPb started_event = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.proto.TaskStartedEventPb, io.littlehorse.proto.TaskStartedEventPb.Builder, io.littlehorse.proto.TaskStartedEventPbOrBuilder> 
        getStartedEventFieldBuilder() {
      if (startedEventBuilder_ == null) {
        startedEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.proto.TaskStartedEventPb, io.littlehorse.proto.TaskStartedEventPb.Builder, io.littlehorse.proto.TaskStartedEventPbOrBuilder>(
                getStartedEvent(),
                getParentForChildren(),
                isClean());
        startedEvent_ = null;
      }
      return startedEventBuilder_;
    }

    private io.littlehorse.proto.TaskCompletedEventPb completedEvent_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.proto.TaskCompletedEventPb, io.littlehorse.proto.TaskCompletedEventPb.Builder, io.littlehorse.proto.TaskCompletedEventPbOrBuilder> completedEventBuilder_;
    /**
     * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
     * @return Whether the completedEvent field is set.
     */
    public boolean hasCompletedEvent() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
     * @return The completedEvent.
     */
    public io.littlehorse.proto.TaskCompletedEventPb getCompletedEvent() {
      if (completedEventBuilder_ == null) {
        return completedEvent_ == null ? io.littlehorse.proto.TaskCompletedEventPb.getDefaultInstance() : completedEvent_;
      } else {
        return completedEventBuilder_.getMessage();
      }
    }
    /**
     * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
     */
    public Builder setCompletedEvent(io.littlehorse.proto.TaskCompletedEventPb value) {
      if (completedEventBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        completedEvent_ = value;
        onChanged();
      } else {
        completedEventBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
     */
    public Builder setCompletedEvent(
        io.littlehorse.proto.TaskCompletedEventPb.Builder builderForValue) {
      if (completedEventBuilder_ == null) {
        completedEvent_ = builderForValue.build();
        onChanged();
      } else {
        completedEventBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
     */
    public Builder mergeCompletedEvent(io.littlehorse.proto.TaskCompletedEventPb value) {
      if (completedEventBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            completedEvent_ != null &&
            completedEvent_ != io.littlehorse.proto.TaskCompletedEventPb.getDefaultInstance()) {
          completedEvent_ =
            io.littlehorse.proto.TaskCompletedEventPb.newBuilder(completedEvent_).mergeFrom(value).buildPartial();
        } else {
          completedEvent_ = value;
        }
        onChanged();
      } else {
        completedEventBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
     */
    public Builder clearCompletedEvent() {
      if (completedEventBuilder_ == null) {
        completedEvent_ = null;
        onChanged();
      } else {
        completedEventBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
     */
    public io.littlehorse.proto.TaskCompletedEventPb.Builder getCompletedEventBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getCompletedEventFieldBuilder().getBuilder();
    }
    /**
     * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
     */
    public io.littlehorse.proto.TaskCompletedEventPbOrBuilder getCompletedEventOrBuilder() {
      if (completedEventBuilder_ != null) {
        return completedEventBuilder_.getMessageOrBuilder();
      } else {
        return completedEvent_ == null ?
            io.littlehorse.proto.TaskCompletedEventPb.getDefaultInstance() : completedEvent_;
      }
    }
    /**
     * <code>.lh_proto.TaskCompletedEventPb completed_event = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.proto.TaskCompletedEventPb, io.littlehorse.proto.TaskCompletedEventPb.Builder, io.littlehorse.proto.TaskCompletedEventPbOrBuilder> 
        getCompletedEventFieldBuilder() {
      if (completedEventBuilder_ == null) {
        completedEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.proto.TaskCompletedEventPb, io.littlehorse.proto.TaskCompletedEventPb.Builder, io.littlehorse.proto.TaskCompletedEventPbOrBuilder>(
                getCompletedEvent(),
                getParentForChildren(),
                isClean());
        completedEvent_ = null;
      }
      return completedEventBuilder_;
    }

    private java.lang.Object wfSpecId_ = "";
    /**
     * <code>string wf_spec_id = 5;</code>
     * @return The wfSpecId.
     */
    public java.lang.String getWfSpecId() {
      java.lang.Object ref = wfSpecId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wfSpecId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string wf_spec_id = 5;</code>
     * @return The bytes for wfSpecId.
     */
    public com.google.protobuf.ByteString
        getWfSpecIdBytes() {
      java.lang.Object ref = wfSpecId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wfSpecId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string wf_spec_id = 5;</code>
     * @param value The wfSpecId to set.
     * @return This builder for chaining.
     */
    public Builder setWfSpecId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wfSpecId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string wf_spec_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWfSpecId() {
      
      wfSpecId_ = getDefaultInstance().getWfSpecId();
      onChanged();
      return this;
    }
    /**
     * <code>string wf_spec_id = 5;</code>
     * @param value The bytes for wfSpecId to set.
     * @return This builder for chaining.
     */
    public Builder setWfSpecIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wfSpecId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lh_proto.WFRunEventPb)
  }

  // @@protoc_insertion_point(class_scope:lh_proto.WFRunEventPb)
  private static final io.littlehorse.proto.WFRunEventPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.proto.WFRunEventPb();
  }

  public static io.littlehorse.proto.WFRunEventPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WFRunEventPb>
      PARSER = new com.google.protobuf.AbstractParser<WFRunEventPb>() {
    @java.lang.Override
    public WFRunEventPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WFRunEventPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WFRunEventPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WFRunEventPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.proto.WFRunEventPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

