// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

/**
 * Protobuf type {@code lh_proto.WFRunRequestPb}
 */
public final class WFRunRequestPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lh_proto.WFRunRequestPb)
    WFRunRequestPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WFRunRequestPb.newBuilder() to construct.
  private WFRunRequestPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WFRunRequestPb() {
    wfRunId_ = "";
    wfSpecId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WFRunRequestPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WFRunRequestPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            wfRunId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            wfSpecId_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              variableValues_ = com.google.protobuf.MapField.newMapField(
                  VariableValuesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.proto.VariableValuePb>
            variableValues__ = input.readMessage(
                VariableValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            variableValues_.getMutableMap().put(
                variableValues__.getKey(), variableValues__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunRequestPb_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetVariableValues();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunRequestPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.proto.WFRunRequestPb.class, io.littlehorse.proto.WFRunRequestPb.Builder.class);
  }

  public static final int WF_RUN_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object wfRunId_;
  /**
   * <code>string wf_run_id = 1;</code>
   * @return The wfRunId.
   */
  @java.lang.Override
  public java.lang.String getWfRunId() {
    java.lang.Object ref = wfRunId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wfRunId_ = s;
      return s;
    }
  }
  /**
   * <code>string wf_run_id = 1;</code>
   * @return The bytes for wfRunId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWfRunIdBytes() {
    java.lang.Object ref = wfRunId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wfRunId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WF_SPEC_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object wfSpecId_;
  /**
   * <code>string wf_spec_id = 2;</code>
   * @return The wfSpecId.
   */
  @java.lang.Override
  public java.lang.String getWfSpecId() {
    java.lang.Object ref = wfSpecId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wfSpecId_ = s;
      return s;
    }
  }
  /**
   * <code>string wf_spec_id = 2;</code>
   * @return The bytes for wfSpecId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWfSpecIdBytes() {
    java.lang.Object ref = wfSpecId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wfSpecId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VARIABLE_VALUES_FIELD_NUMBER = 3;
  private static final class VariableValuesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.littlehorse.proto.VariableValuePb> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.littlehorse.proto.VariableValuePb>newDefaultInstance(
                io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunRequestPb_VariableValuesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.littlehorse.proto.VariableValuePb.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, io.littlehorse.proto.VariableValuePb> variableValues_;
  private com.google.protobuf.MapField<java.lang.String, io.littlehorse.proto.VariableValuePb>
  internalGetVariableValues() {
    if (variableValues_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          VariableValuesDefaultEntryHolder.defaultEntry);
    }
    return variableValues_;
  }

  public int getVariableValuesCount() {
    return internalGetVariableValues().getMap().size();
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
   */

  @java.lang.Override
  public boolean containsVariableValues(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetVariableValues().getMap().containsKey(key);
  }
  /**
   * Use {@link #getVariableValuesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariableValues() {
    return getVariableValuesMap();
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariableValuesMap() {
    return internalGetVariableValues().getMap();
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
   */
  @java.lang.Override

  public io.littlehorse.proto.VariableValuePb getVariableValuesOrDefault(
      java.lang.String key,
      io.littlehorse.proto.VariableValuePb defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
        internalGetVariableValues().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
   */
  @java.lang.Override

  public io.littlehorse.proto.VariableValuePb getVariableValuesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
        internalGetVariableValues().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWfRunIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, wfRunId_);
    }
    if (!getWfSpecIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, wfSpecId_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetVariableValues(),
        VariableValuesDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWfRunIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, wfRunId_);
    }
    if (!getWfSpecIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, wfSpecId_);
    }
    for (java.util.Map.Entry<java.lang.String, io.littlehorse.proto.VariableValuePb> entry
         : internalGetVariableValues().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.proto.VariableValuePb>
      variableValues__ = VariableValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, variableValues__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.proto.WFRunRequestPb)) {
      return super.equals(obj);
    }
    io.littlehorse.proto.WFRunRequestPb other = (io.littlehorse.proto.WFRunRequestPb) obj;

    if (!getWfRunId()
        .equals(other.getWfRunId())) return false;
    if (!getWfSpecId()
        .equals(other.getWfSpecId())) return false;
    if (!internalGetVariableValues().equals(
        other.internalGetVariableValues())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WF_RUN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWfRunId().hashCode();
    hash = (37 * hash) + WF_SPEC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWfSpecId().hashCode();
    if (!internalGetVariableValues().getMap().isEmpty()) {
      hash = (37 * hash) + VARIABLE_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetVariableValues().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.proto.WFRunRequestPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.WFRunRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.proto.WFRunRequestPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lh_proto.WFRunRequestPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lh_proto.WFRunRequestPb)
      io.littlehorse.proto.WFRunRequestPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunRequestPb_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetVariableValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableVariableValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunRequestPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.proto.WFRunRequestPb.class, io.littlehorse.proto.WFRunRequestPb.Builder.class);
    }

    // Construct using io.littlehorse.proto.WFRunRequestPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      wfRunId_ = "";

      wfSpecId_ = "";

      internalGetMutableVariableValues().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFRunRequestPb_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.proto.WFRunRequestPb getDefaultInstanceForType() {
      return io.littlehorse.proto.WFRunRequestPb.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.proto.WFRunRequestPb build() {
      io.littlehorse.proto.WFRunRequestPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.proto.WFRunRequestPb buildPartial() {
      io.littlehorse.proto.WFRunRequestPb result = new io.littlehorse.proto.WFRunRequestPb(this);
      int from_bitField0_ = bitField0_;
      result.wfRunId_ = wfRunId_;
      result.wfSpecId_ = wfSpecId_;
      result.variableValues_ = internalGetVariableValues();
      result.variableValues_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.proto.WFRunRequestPb) {
        return mergeFrom((io.littlehorse.proto.WFRunRequestPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.proto.WFRunRequestPb other) {
      if (other == io.littlehorse.proto.WFRunRequestPb.getDefaultInstance()) return this;
      if (!other.getWfRunId().isEmpty()) {
        wfRunId_ = other.wfRunId_;
        onChanged();
      }
      if (!other.getWfSpecId().isEmpty()) {
        wfSpecId_ = other.wfSpecId_;
        onChanged();
      }
      internalGetMutableVariableValues().mergeFrom(
          other.internalGetVariableValues());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.littlehorse.proto.WFRunRequestPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.littlehorse.proto.WFRunRequestPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object wfRunId_ = "";
    /**
     * <code>string wf_run_id = 1;</code>
     * @return The wfRunId.
     */
    public java.lang.String getWfRunId() {
      java.lang.Object ref = wfRunId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wfRunId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string wf_run_id = 1;</code>
     * @return The bytes for wfRunId.
     */
    public com.google.protobuf.ByteString
        getWfRunIdBytes() {
      java.lang.Object ref = wfRunId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wfRunId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string wf_run_id = 1;</code>
     * @param value The wfRunId to set.
     * @return This builder for chaining.
     */
    public Builder setWfRunId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wfRunId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string wf_run_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWfRunId() {
      
      wfRunId_ = getDefaultInstance().getWfRunId();
      onChanged();
      return this;
    }
    /**
     * <code>string wf_run_id = 1;</code>
     * @param value The bytes for wfRunId to set.
     * @return This builder for chaining.
     */
    public Builder setWfRunIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wfRunId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object wfSpecId_ = "";
    /**
     * <code>string wf_spec_id = 2;</code>
     * @return The wfSpecId.
     */
    public java.lang.String getWfSpecId() {
      java.lang.Object ref = wfSpecId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wfSpecId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string wf_spec_id = 2;</code>
     * @return The bytes for wfSpecId.
     */
    public com.google.protobuf.ByteString
        getWfSpecIdBytes() {
      java.lang.Object ref = wfSpecId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wfSpecId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string wf_spec_id = 2;</code>
     * @param value The wfSpecId to set.
     * @return This builder for chaining.
     */
    public Builder setWfSpecId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wfSpecId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string wf_spec_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWfSpecId() {
      
      wfSpecId_ = getDefaultInstance().getWfSpecId();
      onChanged();
      return this;
    }
    /**
     * <code>string wf_spec_id = 2;</code>
     * @param value The bytes for wfSpecId to set.
     * @return This builder for chaining.
     */
    public Builder setWfSpecIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wfSpecId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, io.littlehorse.proto.VariableValuePb> variableValues_;
    private com.google.protobuf.MapField<java.lang.String, io.littlehorse.proto.VariableValuePb>
    internalGetVariableValues() {
      if (variableValues_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            VariableValuesDefaultEntryHolder.defaultEntry);
      }
      return variableValues_;
    }
    private com.google.protobuf.MapField<java.lang.String, io.littlehorse.proto.VariableValuePb>
    internalGetMutableVariableValues() {
      onChanged();;
      if (variableValues_ == null) {
        variableValues_ = com.google.protobuf.MapField.newMapField(
            VariableValuesDefaultEntryHolder.defaultEntry);
      }
      if (!variableValues_.isMutable()) {
        variableValues_ = variableValues_.copy();
      }
      return variableValues_;
    }

    public int getVariableValuesCount() {
      return internalGetVariableValues().getMap().size();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
     */

    @java.lang.Override
    public boolean containsVariableValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetVariableValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getVariableValuesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariableValues() {
      return getVariableValuesMap();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> getVariableValuesMap() {
      return internalGetVariableValues().getMap();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
     */
    @java.lang.Override

    public io.littlehorse.proto.VariableValuePb getVariableValuesOrDefault(
        java.lang.String key,
        io.littlehorse.proto.VariableValuePb defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
          internalGetVariableValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
     */
    @java.lang.Override

    public io.littlehorse.proto.VariableValuePb getVariableValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> map =
          internalGetVariableValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearVariableValues() {
      internalGetMutableVariableValues().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
     */

    public Builder removeVariableValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableVariableValues().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb>
    getMutableVariableValues() {
      return internalGetMutableVariableValues().getMutableMap();
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
     */
    public Builder putVariableValues(
        java.lang.String key,
        io.littlehorse.proto.VariableValuePb value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableVariableValues().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .lh_proto.VariableValuePb&gt; variable_values = 3;</code>
     */

    public Builder putAllVariableValues(
        java.util.Map<java.lang.String, io.littlehorse.proto.VariableValuePb> values) {
      internalGetMutableVariableValues().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lh_proto.WFRunRequestPb)
  }

  // @@protoc_insertion_point(class_scope:lh_proto.WFRunRequestPb)
  private static final io.littlehorse.proto.WFRunRequestPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.proto.WFRunRequestPb();
  }

  public static io.littlehorse.proto.WFRunRequestPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WFRunRequestPb>
      PARSER = new com.google.protobuf.AbstractParser<WFRunRequestPb>() {
    @java.lang.Override
    public WFRunRequestPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WFRunRequestPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WFRunRequestPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WFRunRequestPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.proto.WFRunRequestPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

