// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

/**
 * Protobuf type {@code lh_proto.WFSpecPb}
 */
public final class WFSpecPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lh_proto.WFSpecPb)
    WFSpecPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WFSpecPb.newBuilder() to construct.
  private WFSpecPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WFSpecPb() {
    id_ = "";
    threadSpecs_ = java.util.Collections.emptyList();
    entrypointThreadName_ = "";
    status_ = 0;
    desiredStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WFSpecPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WFSpecPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdAt_ != null) {
              subBuilder = createdAt_.toBuilder();
            }
            createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdAt_);
              createdAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (updatedAt_ != null) {
              subBuilder = updatedAt_.toBuilder();
            }
            updatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(updatedAt_);
              updatedAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              threadSpecs_ = new java.util.ArrayList<io.littlehorse.proto.ThreadSpecPb>();
              mutable_bitField0_ |= 0x00000001;
            }
            threadSpecs_.add(
                input.readMessage(io.littlehorse.proto.ThreadSpecPb.parser(), extensionRegistry));
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            entrypointThreadName_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            desiredStatus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        threadSpecs_ = java.util.Collections.unmodifiableList(threadSpecs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFSpecPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFSpecPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.proto.WFSpecPb.class, io.littlehorse.proto.WFSpecPb.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return getCreatedAt();
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return Whether the updatedAt field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedAt() {
    return updatedAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return getUpdatedAt();
  }

  public static final int THREAD_SPECS_FIELD_NUMBER = 4;
  private java.util.List<io.littlehorse.proto.ThreadSpecPb> threadSpecs_;
  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  @java.lang.Override
  public java.util.List<io.littlehorse.proto.ThreadSpecPb> getThreadSpecsList() {
    return threadSpecs_;
  }
  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.littlehorse.proto.ThreadSpecPbOrBuilder> 
      getThreadSpecsOrBuilderList() {
    return threadSpecs_;
  }
  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  @java.lang.Override
  public int getThreadSpecsCount() {
    return threadSpecs_.size();
  }
  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.ThreadSpecPb getThreadSpecs(int index) {
    return threadSpecs_.get(index);
  }
  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  @java.lang.Override
  public io.littlehorse.proto.ThreadSpecPbOrBuilder getThreadSpecsOrBuilder(
      int index) {
    return threadSpecs_.get(index);
  }

  public static final int ENTRYPOINT_THREAD_NAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object entrypointThreadName_;
  /**
   * <code>string entrypoint_thread_name = 5;</code>
   * @return The entrypointThreadName.
   */
  @java.lang.Override
  public java.lang.String getEntrypointThreadName() {
    java.lang.Object ref = entrypointThreadName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entrypointThreadName_ = s;
      return s;
    }
  }
  /**
   * <code>string entrypoint_thread_name = 5;</code>
   * @return The bytes for entrypointThreadName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntrypointThreadNameBytes() {
    java.lang.Object ref = entrypointThreadName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entrypointThreadName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private int status_;
  /**
   * <code>.lh_proto.LHStatusPb status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.lh_proto.LHStatusPb status = 6;</code>
   * @return The status.
   */
  @java.lang.Override public io.littlehorse.proto.LHStatusPb getStatus() {
    @SuppressWarnings("deprecation")
    io.littlehorse.proto.LHStatusPb result = io.littlehorse.proto.LHStatusPb.valueOf(status_);
    return result == null ? io.littlehorse.proto.LHStatusPb.UNRECOGNIZED : result;
  }

  public static final int DESIRED_STATUS_FIELD_NUMBER = 7;
  private int desiredStatus_;
  /**
   * <code>.lh_proto.LHStatusPb desired_status = 7;</code>
   * @return The enum numeric value on the wire for desiredStatus.
   */
  @java.lang.Override public int getDesiredStatusValue() {
    return desiredStatus_;
  }
  /**
   * <code>.lh_proto.LHStatusPb desired_status = 7;</code>
   * @return The desiredStatus.
   */
  @java.lang.Override public io.littlehorse.proto.LHStatusPb getDesiredStatus() {
    @SuppressWarnings("deprecation")
    io.littlehorse.proto.LHStatusPb result = io.littlehorse.proto.LHStatusPb.valueOf(desiredStatus_);
    return result == null ? io.littlehorse.proto.LHStatusPb.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (createdAt_ != null) {
      output.writeMessage(2, getCreatedAt());
    }
    if (updatedAt_ != null) {
      output.writeMessage(3, getUpdatedAt());
    }
    for (int i = 0; i < threadSpecs_.size(); i++) {
      output.writeMessage(4, threadSpecs_.get(i));
    }
    if (!getEntrypointThreadNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, entrypointThreadName_);
    }
    if (status_ != io.littlehorse.proto.LHStatusPb.STARTING.getNumber()) {
      output.writeEnum(6, status_);
    }
    if (desiredStatus_ != io.littlehorse.proto.LHStatusPb.STARTING.getNumber()) {
      output.writeEnum(7, desiredStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (createdAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCreatedAt());
    }
    if (updatedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUpdatedAt());
    }
    for (int i = 0; i < threadSpecs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, threadSpecs_.get(i));
    }
    if (!getEntrypointThreadNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, entrypointThreadName_);
    }
    if (status_ != io.littlehorse.proto.LHStatusPb.STARTING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, status_);
    }
    if (desiredStatus_ != io.littlehorse.proto.LHStatusPb.STARTING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, desiredStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.proto.WFSpecPb)) {
      return super.equals(obj);
    }
    io.littlehorse.proto.WFSpecPb other = (io.littlehorse.proto.WFSpecPb) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
    if (hasUpdatedAt()) {
      if (!getUpdatedAt()
          .equals(other.getUpdatedAt())) return false;
    }
    if (!getThreadSpecsList()
        .equals(other.getThreadSpecsList())) return false;
    if (!getEntrypointThreadName()
        .equals(other.getEntrypointThreadName())) return false;
    if (status_ != other.status_) return false;
    if (desiredStatus_ != other.desiredStatus_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasUpdatedAt()) {
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
    }
    if (getThreadSpecsCount() > 0) {
      hash = (37 * hash) + THREAD_SPECS_FIELD_NUMBER;
      hash = (53 * hash) + getThreadSpecsList().hashCode();
    }
    hash = (37 * hash) + ENTRYPOINT_THREAD_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEntrypointThreadName().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + DESIRED_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + desiredStatus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.proto.WFSpecPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.WFSpecPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.WFSpecPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.WFSpecPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.WFSpecPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.proto.WFSpecPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.proto.WFSpecPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.WFSpecPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.WFSpecPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.WFSpecPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.proto.WFSpecPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.proto.WFSpecPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.proto.WFSpecPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lh_proto.WFSpecPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lh_proto.WFSpecPb)
      io.littlehorse.proto.WFSpecPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFSpecPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFSpecPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.proto.WFSpecPb.class, io.littlehorse.proto.WFSpecPb.Builder.class);
    }

    // Construct using io.littlehorse.proto.WFSpecPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getThreadSpecsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (createdAtBuilder_ == null) {
        createdAt_ = null;
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }
      if (updatedAtBuilder_ == null) {
        updatedAt_ = null;
      } else {
        updatedAt_ = null;
        updatedAtBuilder_ = null;
      }
      if (threadSpecsBuilder_ == null) {
        threadSpecs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        threadSpecsBuilder_.clear();
      }
      entrypointThreadName_ = "";

      status_ = 0;

      desiredStatus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.proto.LhProto.internal_static_lh_proto_WFSpecPb_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.proto.WFSpecPb getDefaultInstanceForType() {
      return io.littlehorse.proto.WFSpecPb.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.proto.WFSpecPb build() {
      io.littlehorse.proto.WFSpecPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.proto.WFSpecPb buildPartial() {
      io.littlehorse.proto.WFSpecPb result = new io.littlehorse.proto.WFSpecPb(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (createdAtBuilder_ == null) {
        result.createdAt_ = createdAt_;
      } else {
        result.createdAt_ = createdAtBuilder_.build();
      }
      if (updatedAtBuilder_ == null) {
        result.updatedAt_ = updatedAt_;
      } else {
        result.updatedAt_ = updatedAtBuilder_.build();
      }
      if (threadSpecsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          threadSpecs_ = java.util.Collections.unmodifiableList(threadSpecs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.threadSpecs_ = threadSpecs_;
      } else {
        result.threadSpecs_ = threadSpecsBuilder_.build();
      }
      result.entrypointThreadName_ = entrypointThreadName_;
      result.status_ = status_;
      result.desiredStatus_ = desiredStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.proto.WFSpecPb) {
        return mergeFrom((io.littlehorse.proto.WFSpecPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.proto.WFSpecPb other) {
      if (other == io.littlehorse.proto.WFSpecPb.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasUpdatedAt()) {
        mergeUpdatedAt(other.getUpdatedAt());
      }
      if (threadSpecsBuilder_ == null) {
        if (!other.threadSpecs_.isEmpty()) {
          if (threadSpecs_.isEmpty()) {
            threadSpecs_ = other.threadSpecs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureThreadSpecsIsMutable();
            threadSpecs_.addAll(other.threadSpecs_);
          }
          onChanged();
        }
      } else {
        if (!other.threadSpecs_.isEmpty()) {
          if (threadSpecsBuilder_.isEmpty()) {
            threadSpecsBuilder_.dispose();
            threadSpecsBuilder_ = null;
            threadSpecs_ = other.threadSpecs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            threadSpecsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getThreadSpecsFieldBuilder() : null;
          } else {
            threadSpecsBuilder_.addAllMessages(other.threadSpecs_);
          }
        }
      }
      if (!other.getEntrypointThreadName().isEmpty()) {
        entrypointThreadName_ = other.entrypointThreadName_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.desiredStatus_ != 0) {
        setDesiredStatusValue(other.getDesiredStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.littlehorse.proto.WFSpecPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.littlehorse.proto.WFSpecPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return createdAtBuilder_ != null || createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
        onChanged();
      } else {
        createdAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
        onChanged();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (createdAt_ != null) {
          createdAt_ =
            com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
        } else {
          createdAt_ = value;
        }
        onChanged();
      } else {
        createdAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder clearCreatedAt() {
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
        onChanged();
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp updatedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return updatedAtBuilder_ != null || updatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedAt_ = value;
        onChanged();
      } else {
        updatedAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
        onChanged();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (updatedAt_ != null) {
          updatedAt_ =
            com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
        } else {
          updatedAt_ = value;
        }
        onChanged();
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public Builder clearUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = null;
        onChanged();
      } else {
        updatedAt_ = null;
        updatedAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      
      onChanged();
      return getUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }

    private java.util.List<io.littlehorse.proto.ThreadSpecPb> threadSpecs_ =
      java.util.Collections.emptyList();
    private void ensureThreadSpecsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        threadSpecs_ = new java.util.ArrayList<io.littlehorse.proto.ThreadSpecPb>(threadSpecs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.proto.ThreadSpecPb, io.littlehorse.proto.ThreadSpecPb.Builder, io.littlehorse.proto.ThreadSpecPbOrBuilder> threadSpecsBuilder_;

    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public java.util.List<io.littlehorse.proto.ThreadSpecPb> getThreadSpecsList() {
      if (threadSpecsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(threadSpecs_);
      } else {
        return threadSpecsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public int getThreadSpecsCount() {
      if (threadSpecsBuilder_ == null) {
        return threadSpecs_.size();
      } else {
        return threadSpecsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public io.littlehorse.proto.ThreadSpecPb getThreadSpecs(int index) {
      if (threadSpecsBuilder_ == null) {
        return threadSpecs_.get(index);
      } else {
        return threadSpecsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public Builder setThreadSpecs(
        int index, io.littlehorse.proto.ThreadSpecPb value) {
      if (threadSpecsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThreadSpecsIsMutable();
        threadSpecs_.set(index, value);
        onChanged();
      } else {
        threadSpecsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public Builder setThreadSpecs(
        int index, io.littlehorse.proto.ThreadSpecPb.Builder builderForValue) {
      if (threadSpecsBuilder_ == null) {
        ensureThreadSpecsIsMutable();
        threadSpecs_.set(index, builderForValue.build());
        onChanged();
      } else {
        threadSpecsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public Builder addThreadSpecs(io.littlehorse.proto.ThreadSpecPb value) {
      if (threadSpecsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThreadSpecsIsMutable();
        threadSpecs_.add(value);
        onChanged();
      } else {
        threadSpecsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public Builder addThreadSpecs(
        int index, io.littlehorse.proto.ThreadSpecPb value) {
      if (threadSpecsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThreadSpecsIsMutable();
        threadSpecs_.add(index, value);
        onChanged();
      } else {
        threadSpecsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public Builder addThreadSpecs(
        io.littlehorse.proto.ThreadSpecPb.Builder builderForValue) {
      if (threadSpecsBuilder_ == null) {
        ensureThreadSpecsIsMutable();
        threadSpecs_.add(builderForValue.build());
        onChanged();
      } else {
        threadSpecsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public Builder addThreadSpecs(
        int index, io.littlehorse.proto.ThreadSpecPb.Builder builderForValue) {
      if (threadSpecsBuilder_ == null) {
        ensureThreadSpecsIsMutable();
        threadSpecs_.add(index, builderForValue.build());
        onChanged();
      } else {
        threadSpecsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public Builder addAllThreadSpecs(
        java.lang.Iterable<? extends io.littlehorse.proto.ThreadSpecPb> values) {
      if (threadSpecsBuilder_ == null) {
        ensureThreadSpecsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, threadSpecs_);
        onChanged();
      } else {
        threadSpecsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public Builder clearThreadSpecs() {
      if (threadSpecsBuilder_ == null) {
        threadSpecs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        threadSpecsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public Builder removeThreadSpecs(int index) {
      if (threadSpecsBuilder_ == null) {
        ensureThreadSpecsIsMutable();
        threadSpecs_.remove(index);
        onChanged();
      } else {
        threadSpecsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public io.littlehorse.proto.ThreadSpecPb.Builder getThreadSpecsBuilder(
        int index) {
      return getThreadSpecsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public io.littlehorse.proto.ThreadSpecPbOrBuilder getThreadSpecsOrBuilder(
        int index) {
      if (threadSpecsBuilder_ == null) {
        return threadSpecs_.get(index);  } else {
        return threadSpecsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public java.util.List<? extends io.littlehorse.proto.ThreadSpecPbOrBuilder> 
         getThreadSpecsOrBuilderList() {
      if (threadSpecsBuilder_ != null) {
        return threadSpecsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(threadSpecs_);
      }
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public io.littlehorse.proto.ThreadSpecPb.Builder addThreadSpecsBuilder() {
      return getThreadSpecsFieldBuilder().addBuilder(
          io.littlehorse.proto.ThreadSpecPb.getDefaultInstance());
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public io.littlehorse.proto.ThreadSpecPb.Builder addThreadSpecsBuilder(
        int index) {
      return getThreadSpecsFieldBuilder().addBuilder(
          index, io.littlehorse.proto.ThreadSpecPb.getDefaultInstance());
    }
    /**
     * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
     */
    public java.util.List<io.littlehorse.proto.ThreadSpecPb.Builder> 
         getThreadSpecsBuilderList() {
      return getThreadSpecsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.proto.ThreadSpecPb, io.littlehorse.proto.ThreadSpecPb.Builder, io.littlehorse.proto.ThreadSpecPbOrBuilder> 
        getThreadSpecsFieldBuilder() {
      if (threadSpecsBuilder_ == null) {
        threadSpecsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.littlehorse.proto.ThreadSpecPb, io.littlehorse.proto.ThreadSpecPb.Builder, io.littlehorse.proto.ThreadSpecPbOrBuilder>(
                threadSpecs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        threadSpecs_ = null;
      }
      return threadSpecsBuilder_;
    }

    private java.lang.Object entrypointThreadName_ = "";
    /**
     * <code>string entrypoint_thread_name = 5;</code>
     * @return The entrypointThreadName.
     */
    public java.lang.String getEntrypointThreadName() {
      java.lang.Object ref = entrypointThreadName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entrypointThreadName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string entrypoint_thread_name = 5;</code>
     * @return The bytes for entrypointThreadName.
     */
    public com.google.protobuf.ByteString
        getEntrypointThreadNameBytes() {
      java.lang.Object ref = entrypointThreadName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entrypointThreadName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entrypoint_thread_name = 5;</code>
     * @param value The entrypointThreadName to set.
     * @return This builder for chaining.
     */
    public Builder setEntrypointThreadName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      entrypointThreadName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string entrypoint_thread_name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntrypointThreadName() {
      
      entrypointThreadName_ = getDefaultInstance().getEntrypointThreadName();
      onChanged();
      return this;
    }
    /**
     * <code>string entrypoint_thread_name = 5;</code>
     * @param value The bytes for entrypointThreadName to set.
     * @return This builder for chaining.
     */
    public Builder setEntrypointThreadNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      entrypointThreadName_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.lh_proto.LHStatusPb status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.lh_proto.LHStatusPb status = 6;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.lh_proto.LHStatusPb status = 6;</code>
     * @return The status.
     */
    @java.lang.Override
    public io.littlehorse.proto.LHStatusPb getStatus() {
      @SuppressWarnings("deprecation")
      io.littlehorse.proto.LHStatusPb result = io.littlehorse.proto.LHStatusPb.valueOf(status_);
      return result == null ? io.littlehorse.proto.LHStatusPb.UNRECOGNIZED : result;
    }
    /**
     * <code>.lh_proto.LHStatusPb status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(io.littlehorse.proto.LHStatusPb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.lh_proto.LHStatusPb status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private int desiredStatus_ = 0;
    /**
     * <code>.lh_proto.LHStatusPb desired_status = 7;</code>
     * @return The enum numeric value on the wire for desiredStatus.
     */
    @java.lang.Override public int getDesiredStatusValue() {
      return desiredStatus_;
    }
    /**
     * <code>.lh_proto.LHStatusPb desired_status = 7;</code>
     * @param value The enum numeric value on the wire for desiredStatus to set.
     * @return This builder for chaining.
     */
    public Builder setDesiredStatusValue(int value) {
      
      desiredStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.lh_proto.LHStatusPb desired_status = 7;</code>
     * @return The desiredStatus.
     */
    @java.lang.Override
    public io.littlehorse.proto.LHStatusPb getDesiredStatus() {
      @SuppressWarnings("deprecation")
      io.littlehorse.proto.LHStatusPb result = io.littlehorse.proto.LHStatusPb.valueOf(desiredStatus_);
      return result == null ? io.littlehorse.proto.LHStatusPb.UNRECOGNIZED : result;
    }
    /**
     * <code>.lh_proto.LHStatusPb desired_status = 7;</code>
     * @param value The desiredStatus to set.
     * @return This builder for chaining.
     */
    public Builder setDesiredStatus(io.littlehorse.proto.LHStatusPb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      desiredStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.lh_proto.LHStatusPb desired_status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesiredStatus() {
      
      desiredStatus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lh_proto.WFSpecPb)
  }

  // @@protoc_insertion_point(class_scope:lh_proto.WFSpecPb)
  private static final io.littlehorse.proto.WFSpecPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.proto.WFSpecPb();
  }

  public static io.littlehorse.proto.WFSpecPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WFSpecPb>
      PARSER = new com.google.protobuf.AbstractParser<WFSpecPb>() {
    @java.lang.Override
    public WFSpecPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WFSpecPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WFSpecPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WFSpecPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.proto.WFSpecPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

