// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.proto;

public interface WFSpecPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lh_proto.WFSpecPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  java.util.List<io.littlehorse.proto.ThreadSpecPb> 
      getThreadSpecsList();
  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  io.littlehorse.proto.ThreadSpecPb getThreadSpecs(int index);
  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  int getThreadSpecsCount();
  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  java.util.List<? extends io.littlehorse.proto.ThreadSpecPbOrBuilder> 
      getThreadSpecsOrBuilderList();
  /**
   * <code>repeated .lh_proto.ThreadSpecPb thread_specs = 4;</code>
   */
  io.littlehorse.proto.ThreadSpecPbOrBuilder getThreadSpecsOrBuilder(
      int index);

  /**
   * <code>string entrypoint_thread_name = 5;</code>
   * @return The entrypointThreadName.
   */
  java.lang.String getEntrypointThreadName();
  /**
   * <code>string entrypoint_thread_name = 5;</code>
   * @return The bytes for entrypointThreadName.
   */
  com.google.protobuf.ByteString
      getEntrypointThreadNameBytes();

  /**
   * <code>.lh_proto.LHStatusPb status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.lh_proto.LHStatusPb status = 6;</code>
   * @return The status.
   */
  io.littlehorse.proto.LHStatusPb getStatus();

  /**
   * <code>.lh_proto.LHStatusPb desired_status = 7;</code>
   * @return The enum numeric value on the wire for desiredStatus.
   */
  int getDesiredStatusValue();
  /**
   * <code>.lh_proto.LHStatusPb desired_status = 7;</code>
   * @return The desiredStatus.
   */
  io.littlehorse.proto.LHStatusPb getDesiredStatus();
}
