/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package little.horse;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.databind.ObjectMapper;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("TODO: run some experiment for funsies.");
        System.out.println("This class does nothing, all the logic is elsewhere.");

        Double dub = 2.5;
        Map<String, Object> m = new HashMap<>();
        m.put("foo", dub);
        System.out.println(new ObjectMapper().writeValueAsString(m));
    }
}
