/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package little.horse;

import little.horse.lib.Config;

public class App {

    public static void main(String[] args) {
        Config config = null;
        config = new Config();
        LittleHorseAPI lapi = new LittleHorseAPI(config);
        Runtime.getRuntime().addShutdownHook(new Thread(config::cleanup));
        Runtime.getRuntime().addShutdownHook(new Thread(lapi::cleanup));
        lapi.run();
    }
}
