apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
    io.littlehorse/active: true
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      io.littlehorse/active: true
  template:
    metadata:
      labels:
        app: postgres
	io.littlehorse/active: true
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
	  value: postgres
	- name: POSTGRES_USER
	  value: postgres
	- name: POSTGRES_PASSWORD
	  value: postgres
        image: postgres:10.4
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    io.littlehorse/active: true
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
    io.littlehorse/active: true
  type: ClusterIP

